// Code generated by tygo. DO NOT EDIT.
/**
 * This file is auto-generated by tygo. DO NOT EDIT DIRECTLY.
 * Master schema: pkg/model/*.go (Ref: ADR-0004)
 */

//////////
// source: admin.go

/**
 * UpdateMemberPenlightRequest represents the payload to update a member's penlight colors.
 */
export interface UpdateMemberPenlightRequest {
  left_color_id: ID;
  right_color_id: ID;
  ordered: boolean;
}
/**
 * UpdateMemberStatusRequest represents the payload to update a member's activity status and/or generation.
 */
export interface UpdateMemberStatusRequest {
  status?: MemberStatus;
  generation?: number /* int */;
}
/**
 * SetPrimaryMemberImageRequest represents the payload to set a member's primary/default image.
 */
export interface SetPrimaryMemberImageRequest {
  image_id: ID;
}
/**
 * UpdateMemberImagePhotoTypeRequest represents the payload to update a member image's costume/photo category.
 */
export interface UpdateMemberImagePhotoTypeRequest {
  photo_type_id: ID;
}

//////////
// source: answer.go

/**
 * AnswerLog records an individual quiz question response by a user for statistics and review.
 */
export interface AnswerLog {
  id: ID;
  user_id: ID;
  quiz_question_id: ID;
  target_member_id?: ID; // mem_... (メンバー問題時)
  target_song_id?: ID; // sng_... (楽曲問題時)
  group_id: ID;
  is_correct: boolean;
  response_time_ms: number /* int */;
  answered_at: string;
}

//////////
// source: color.go

/**
 * Color represents an official penlight color.
 * Colors can be group-specific or shared standard colors (when GroupID is nil).
 */
export interface Color {
  id: ID; // col_... (UUID v7)
  group_id?: ID; // Optional group owner, nil for common/standard colors
  name: string; // Color name, e.g. "スカイブルー", "パステルブルー", "青"
  hex_code: string; // Hex color code, e.g. "#00BFFF", "#7CC7E8"
  display_order: number /* int */; // UI sort order within the color selector
  created_at: string;
  updated_at: string;
}

//////////
// source: dto.go

/**
 * BootstrapResponse contains all master records required for offline PWA operation (Ref: ADR-0007, ADR-0026, ADR-0027).
 */
export interface BootstrapResponse {
  series: Series[];
  groups: Group[];
  colors: Color[];
  members: Member[];
  songs: Song[];
  generated_at: string;
}
/**
 * GenerateQuizRequest holds query parameters for quiz generation.
 */
export interface GenerateQuizRequest {
  group_id?: ID;
  generation?: number /* int */;
  strategy: string; // random, similar_color, spaced_repetition
  count: number /* int */; // 1-10
}
/**
 * GenerateQuizResponse returns dynamically generated 4-choice questions.
 */
export interface GenerateQuizResponse {
  questions: QuizQuestion[];
}
/**
 * SubmitAnswerRequest represents a single quiz answer submission.
 */
export interface SubmitAnswerRequest {
  quiz_question_id: ID;
  target_member_id: ID;
  selected_member_id: ID;
  response_time_ms: number /* int */;
}
/**
 * SubmitAnswerResponse returns immediate grading and explanation.
 */
export interface SubmitAnswerResponse {
  is_correct: boolean;
  correct_member_id: ID;
  answer_log_id: ID;
}
/**
 * BatchAnswerItem represents an offline queued answer record (Ref: ADR-0007, ADR-0032).
 */
export interface BatchAnswerItem {
  id: ID; // Pre-generated ans_<uuidv7> (idempotency key)
  user_id?: ID;
  quiz_question_id: ID;
  target_member_id?: ID; // mem_... (メンバー問題時)
  target_song_id?: ID; // sng_... (楽曲問題時)
  group_id: ID;
  is_correct: boolean;
  response_time_ms: number /* int */;
  answered_at: string;
}
/**
 * BatchAnswerRequest holds multiple offline answer logs.
 */
export interface BatchAnswerRequest {
  answers: BatchAnswerItem[];
}
/**
 * BatchAnswerResponse returns the count of successfully synchronized items.
 */
export interface BatchAnswerResponse {
  synced_count: number /* int */;
  synced_ids: ID[];
}
/**
 * UserStatisticsResponse returns aggregated metrics for a user.
 */
export interface UserStatisticsResponse {
  total_answers: number /* int */;
  total_correct: number /* int */;
  accuracy_rate: number /* float64 */;
  average_response_time_ms: number /* int */;
}
/**
 * TargetType indicates the entity type for quiz statistics (member / song / etc.).
 */
export type TargetType = string;
export const TargetTypeMember: TargetType = "member";
export const TargetTypeSong: TargetType = "song";
/**
 * TargetStat represents performance statistics for a specific target.
 */
export interface TargetStat {
  target_id: ID; // mem_... or sng_...
  target_type: TargetType; // member / song
  group_id: ID; // grp_...
  name: string; // メンバー名 / 楽曲名
  total_answers: number /* int */;
  correct_answers: number /* int */;
  accuracy_rate: number /* float64 */; // 0.0 ~ 1.0
  average_response_time_ms: number /* int */;
  metadata?: { [key: string]: any}; // 任意付加情報 (kana, last_answered_at, streak等)
}
/**
 * GroupStat represents aggregated metrics for an idol group.
 */
export interface GroupStat {
  group_id: ID;
  group_name: string;
  total_answers: number /* int */;
  correct_answers: number /* int */;
  accuracy_rate: number /* float64 */;
  average_response_time_ms: number /* int */;
  metadata?: { [key: string]: any}; // 任意付加情報 (series_id, rank等)
}
/**
 * QuizStatisticsFilter specifies criteria for filtering quiz statistics.
 */
export interface QuizStatisticsFilter {
  UserID?: ID;
  GroupID?: ID;
  TargetType?: TargetType;
  Limit: number /* int */; // limit for weak targets (default: 5)
}
/**
 * QuizStatisticsResponse holds core analytical data and flexible extras (Ref: ADR-0032).
 */
export interface QuizStatisticsResponse {
  total_answers: number /* int */;
  total_correct: number /* int */;
  accuracy_rate: number /* float64 */;
  average_response_time_ms: number /* int */;
  groups?: GroupStat[];
  weak_targets?: TargetStat[]; // 苦手克服向けワーストN件
  extra?: { [key: string]: any}; // 将来の拡張・実験的集計データ
}

//////////
// source: error.go

/**
 * Standard error codes (The 6 essential codes from ADR-0014)
 */
export const CodeInvalidParams = "INVALID_PARAMS";
/**
 * Standard error codes (The 6 essential codes from ADR-0014)
 */
export const CodeUnauthorized = "UNAUTHORIZED";
/**
 * Standard error codes (The 6 essential codes from ADR-0014)
 */
export const CodeForbidden = "FORBIDDEN";
/**
 * Standard error codes (The 6 essential codes from ADR-0014)
 */
export const CodeNotFound = "NOT_FOUND";
/**
 * Standard error codes (The 6 essential codes from ADR-0014)
 */
export const CodeInsufficientMembers = "INSUFFICIENT_MEMBERS";
/**
 * Standard error codes (The 6 essential codes from ADR-0014)
 */
export const CodeInternalError = "INTERNAL_ERROR";
/**
 * ParamError records an individual invalid request parameter.
 */
export interface ParamError {
  field: string;
  message: string;
}
/**
 * AppError represents an RFC 9457 Problem Details error payload schema.
 */
export interface AppError {
  status: number /* int */;
  code: string;
  title: string;
  detail: string;
  invalid_params?: ParamError[];
}

//////////
// source: group.go

/**
 * Group represents an idol group entity (e.g. Hinatazaka46, Sakurazaka46, Nogizaka46, Aobazaka46).
 * It is designed to be fully open for dynamic extension without any enum hardcoding or code changes.
 */
export interface Group {
  id: ID; // grp_... (UUID v7)
  series_id: ID; // ser_... (UUID v7)
  name: string; // Formal name, e.g. "日向坂46"
  short_name: string; // Short display name, e.g. "日向坂"
  slug: string; // URL-safe identifier, e.g. "hinatazaka46", "aobazaka46"
  theme_color_hex: string; // Official theme color, e.g. "#7CC7E8"
  display_order: number /* int */; // UI sort order
  is_active: boolean; // Active status
  created_at: string;
  updated_at: string;
}

//////////
// source: id.go

/**
 * Prefix defines typed entity identifier prefixes (TypeID convention).
 */
export type Prefix = string;
export const PrefixSeries: Prefix = "ser"; // Series: ser_<uuidv7>
export const PrefixGroup: Prefix = "grp"; // Group: grp_<uuidv7>
export const PrefixColor: Prefix = "col"; // Color: col_<uuidv7>
export const PrefixMember: Prefix = "mem"; // Member: mem_<uuidv7>
export const PrefixSong: Prefix = "sng"; // Song: sng_<uuidv7>
export const PrefixImage: Prefix = "img"; // Member Image: img_<uuidv7>
export const PrefixPhotoType: Prefix = "pht"; // Photo Type: pht_<uuidv7>
export const PrefixQuiz: Prefix = "quiz"; // Quiz Question: quiz_<uuidv7>
export const PrefixUser: Prefix = "usr"; // User: usr_<uuidv7>
export const PrefixAnswer: Prefix = "ans"; // Answer Log: ans_<uuidv7>
/**
 * ID represents a prefixed UUID v7 identifier (e.g., mem_018f3a5b8c9d7a1e8f2b3c4d5e6f7a8b).
 * The prefix prevents accidental misuse across entity types, while UUID v7 provides
 * time-sortable, globally unique surrogate keys.
 */
export type ID = string;

//////////
// source: master_version.go

/**
 * CurrentMasterVersion defines the canonical version of master data (seeds/data/*.json).
 */
export const CurrentMasterVersion = "2026.10.05-3";
/**
 * MasterVersion tracks the current master data synchronization version (Ref: ADR-0021).
 */
export interface MasterVersion {
  id: string; // "current"
  version: string; // Git commit hash or semantic version
  updated_at: string;
}

//////////
// source: member.go

/**
 * MemberStatus represents the member's current active status.
 */
export type MemberStatus = string;
export const StatusActive: MemberStatus = "active"; // 現役活動中
export const StatusGraduated: MemberStatus = "graduated"; // 卒業
export const StatusHiatus: MemberStatus = "hiatus"; // 休業中
/**
 * PenlightPair holds the two penlight colors assigned to a member.
 */
export interface PenlightPair {
  left_color_id: ID; // col_... (Left hand / Color 1)
  right_color_id: ID; // col_... (Right hand / Color 2)
  ordered: boolean; // true if position matters, false if symmetric
}
/**
 * MemberImage represents an image asset associated with a member (Ref: ADR-0021).
 */
export interface MemberImage {
  id: ID; // img_... (UUID v7 surrogate key)
  member_id: ID; // mem_... (FK)
  photo_type_id: ID; // pht_... (FK, Ref: ADR-0021)
  photo_type?: PhotoType; // Associated costume/photo category
  image_key: string; // Immutable image filename: e.g. "img_<uuidv7>.webp"
  is_primary: boolean; // true for the primary/default image
  display_order: number /* int */;
  created_at: string;
  updated_at: string;
}
/**
 * Member represents an idol member.
 * Natural keys (names) are never used as identifiers to prevent collisions on homonyms or name changes.
 */
export interface Member {
  id: ID; // mem_... (UUID v7 immutable surrogate key)
  group_id: ID; // grp_...
  family_name: string; // e.g. "加藤"
  given_name: string; // e.g. "史帆"
  family_name_kana: string; // e.g. "かとう"
  given_name_kana: string; // e.g. "しほ"
  generation: number /* int */; // e.g. 1 (1期生)
  status: MemberStatus; // active, graduated, hiatus
  penlight: PenlightPair; // Assigned penlight colors
  images?: MemberImage[]; // Associated images (1:N, Ref: ADR-0021)
  joined_at?: string; // Optional joining date
  graduated_at?: string; // Optional graduation date
  verified_at?: string; // Timestamp when metadata was verified
  created_at: string;
  updated_at: string;
}

//////////
// source: photo_type.go

/**
 * PhotoType represents a costume or photo category (Ref: ADR-0021).
 */
export interface PhotoType {
  id: ID; // pht_... (UUID v7 surrogate key)
  group_id: ID; // grp_... (FK)
  slug: string; // e.g. "13th_single", "2nd_album"
  name: string; // e.g. "13th Single 制服", "2nd Album アー写"
  display_order: number /* int */;
  created_at: string;
  updated_at: string;
}

//////////
// source: quiz.go

/**
 * QuizOption represents one of the choices in a 4-choice penlight quiz.
 */
export interface QuizOption {
  member_id: ID;
  member_name: string;
  generation: number /* int */;
  penlight: PenlightPair;
  left_hex: string;
  right_hex: string;
  left_name: string;
  right_name: string;
  is_correct: boolean;
}
/**
 * QuizQuestion represents a 4-choice penlight quiz question.
 */
export interface QuizQuestion {
  id: ID; // quiz_... (UUID v7)
  target_member_id: ID; // mem_...
  target_member: Member;
  options: QuizOption[]; // Exactly 4 options
  correct_index: number /* int */; // 0-3
  generated_at: string;
}
/**
 * QuizFilter specifies candidate pool filtering criteria (Ref: ADR-0018, ADR-0026, ADR-0029).
 */
export interface QuizFilter {
  series_id?: ID;
  group_id?: ID;
  generations?: number /* int */[];
  photo_type_ids?: ID[];
  include_graduated: boolean;
  song_mode: boolean; // true: 楽曲カラークイズ, false: メンバーカラークイズ (ADR-0029)
}

//////////
// source: repository.go

/**
 * Repository defines data access operations required by the domain and HTTP handlers.
 * Following ADR-0004 and ADR-0017, this interface uses only Go standard library and
 * model package types to preserve zero external dependencies in the model layer.
 */
export type Repository = any;

//////////
// source: series.go

/**
 * Series represents an idol franchise or series (e.g. "坂道シリーズ", "イコノイジョイ").
 */
export interface Series {
  id: ID; // ser_... (UUID v7)
  name: string; // Formal name, e.g. "坂道シリーズ", "イコノイジョイ"
  slug: string; // URL-safe identifier, e.g. "sakamichi", "ikolove"
  display_order: number /* int */; // UI sort order
  created_at: string;
  updated_at: string;
}

//////////
// source: song.go

/**
 * Song represents a musical track entity and its official/live penlight colors.
 */
export interface Song {
  id: ID; // sng_... (UUID v7)
  group_id: ID; // 所属グループ (grp_...)
  title: string; // 楽曲タイトル (例: "絶対アイドル辞めないで")
  kana?: string; // 読み仮名 (任意・未設定可, ソート補助用)
  color1_id: ID; // 1色目 (必須, col_...)
  color2_id?: ID; // 2色目 (任意, col_...。1色の曲は nil)
  created_at: string;
  updated_at: string;
}

//////////
// source: user.go

/**
 * User represents an authenticated or registered user.
 */
export interface User {
  id: ID; // usr_<uuidv7>
  google_sub?: string; // Google OIDC unique subject ID
  email?: string; // Google account email address
  display_name: string; // User public display name
  avatar_url: string; // Avatar image URL
  created_at: string;
  last_login_at: string;
}
