// Code generated by tygo. DO NOT EDIT.
/**
 * This file is auto-generated by tygo. DO NOT EDIT DIRECTLY.
 * Master schema: pkg/model/*.go (Ref: ADR-0004)
 */

//////////
// source: answer.go

/**
 * AnswerLog records an individual quiz question response by a user for statistics and review.
 */
export interface AnswerLog {
  id: ID; // ans_<uuidv7>
  user_id: ID; // usr_<uuidv7>
  quiz_question_id: ID; // quiz_<uuidv7>
  target_member_id: ID; // mem_<uuidv7>
  group_id: ID; // grp_<uuidv7> (for fast aggregation)
  is_correct: boolean; // whether the answer was correct
  response_time_ms: number /* int */; // reaction time in milliseconds
  answered_at: string; // timestamp of answer
}

//////////
// source: color.go

/**
 * Color represents an official penlight color.
 * Colors can be group-specific or shared standard colors (when GroupID is nil).
 */
export interface Color {
  id: ID; // col_... (UUID v7)
  group_id?: ID; // Optional group owner, nil for common/standard colors
  name: string; // Color name, e.g. "スカイブルー", "パステルブルー", "青"
  hex_code: string; // Hex color code, e.g. "#00BFFF", "#7CC7E8"
  display_order: number /* int */; // UI sort order within the color selector
  created_at: string;
  updated_at: string;
}

//////////
// source: dto.go

/**
 * BootstrapResponse contains all master records required for offline PWA operation.
 */
export interface BootstrapResponse {
  groups: Group[];
  colors: Color[];
  members: Member[];
  generated_at: string;
}
/**
 * GenerateQuizRequest holds query parameters for quiz generation.
 */
export interface GenerateQuizRequest {
  group_id?: ID;
  generation?: number /* int */;
  strategy: string; // random, similar_color, spaced_repetition
  count: number /* int */; // 1-10
}
/**
 * GenerateQuizResponse returns dynamically generated 4-choice questions.
 */
export interface GenerateQuizResponse {
  questions: QuizQuestion[];
}
/**
 * SubmitAnswerRequest represents a single quiz answer submission.
 */
export interface SubmitAnswerRequest {
  quiz_question_id: ID;
  target_member_id: ID;
  selected_member_id: ID;
  response_time_ms: number /* int */;
}
/**
 * SubmitAnswerResponse returns immediate grading and explanation.
 */
export interface SubmitAnswerResponse {
  is_correct: boolean;
  correct_member_id: ID;
  answer_log_id: ID;
}
/**
 * BatchAnswerItem represents an offline queued answer record.
 */
export interface BatchAnswerItem {
  id: ID; // Pre-generated ans_<uuidv7> (idempotency key)
  quiz_question_id: ID;
  target_member_id: ID;
  group_id: ID;
  is_correct: boolean;
  response_time_ms: number /* int */;
  answered_at: string;
}
/**
 * BatchAnswerRequest holds multiple offline answer logs.
 */
export interface BatchAnswerRequest {
  answers: BatchAnswerItem[];
}
/**
 * BatchAnswerResponse returns the count of successfully synchronized items.
 */
export interface BatchAnswerResponse {
  synced_count: number /* int */;
  synced_ids: ID[];
}
/**
 * UserStatisticsResponse returns aggregated metrics for a user.
 */
export interface UserStatisticsResponse {
  total_answers: number /* int */;
  total_correct: number /* int */;
  accuracy_rate: number /* float64 */;
  average_response_time_ms: number /* int */;
}

//////////
// source: error.go

/**
 * Standard error codes (The 6 essential codes from ADR-0014)
 */
export const CodeInvalidParams = "INVALID_PARAMS";
/**
 * Standard error codes (The 6 essential codes from ADR-0014)
 */
export const CodeUnauthorized = "UNAUTHORIZED";
/**
 * Standard error codes (The 6 essential codes from ADR-0014)
 */
export const CodeForbidden = "FORBIDDEN";
/**
 * Standard error codes (The 6 essential codes from ADR-0014)
 */
export const CodeNotFound = "NOT_FOUND";
/**
 * Standard error codes (The 6 essential codes from ADR-0014)
 */
export const CodeInsufficientMembers = "INSUFFICIENT_MEMBERS";
/**
 * Standard error codes (The 6 essential codes from ADR-0014)
 */
export const CodeInternalError = "INTERNAL_ERROR";
/**
 * ParamError records an individual invalid request parameter.
 */
export interface ParamError {
  field: string;
  message: string;
}
/**
 * AppError represents an RFC 9457 Problem Details error payload schema.
 */
export interface AppError {
  status: number /* int */;
  code: string;
  title: string;
  detail: string;
  invalid_params?: ParamError[];
}

//////////
// source: group.go

/**
 * Group represents an idol group entity (e.g. Hinatazaka46, Sakurazaka46, Nogizaka46, Aobazaka46).
 * It is designed to be fully open for dynamic extension without any enum hardcoding or code changes.
 */
export interface Group {
  id: ID; // grp_... (UUID v7)
  name: string; // Formal name, e.g. "日向坂46"
  short_name: string; // Short display name, e.g. "日向坂"
  slug: string; // URL-safe identifier, e.g. "hinatazaka46", "aobazaka46"
  theme_color_hex: string; // Official theme color, e.g. "#7CC7E8"
  display_order: number /* int */; // UI sort order
  is_active: boolean; // Active status
  created_at: string;
  updated_at: string;
}

//////////
// source: id.go

/**
 * Prefix defines typed entity identifier prefixes (TypeID convention).
 */
export type Prefix = string;
export const PrefixGroup: Prefix = "grp"; // Group: grp_<uuidv7>
export const PrefixColor: Prefix = "col"; // Color: col_<uuidv7>
export const PrefixMember: Prefix = "mem"; // Member: mem_<uuidv7>
export const PrefixQuiz: Prefix = "quiz"; // Quiz Question: quiz_<uuidv7>
export const PrefixUser: Prefix = "usr"; // User: usr_<uuidv7>
export const PrefixAnswer: Prefix = "ans"; // Answer Log: ans_<uuidv7>
/**
 * ID represents a prefixed UUID v7 identifier (e.g., mem_018f3a5b8c9d7a1e8f2b3c4d5e6f7a8b).
 * The prefix prevents accidental misuse across entity types, while UUID v7 provides
 * time-sortable, globally unique surrogate keys.
 */
export type ID = string;

//////////
// source: member.go

/**
 * MemberStatus represents the member's current active status.
 */
export type MemberStatus = string;
export const StatusActive: MemberStatus = "active"; // 現役活動中
export const StatusGraduated: MemberStatus = "graduated"; // 卒業
export const StatusHiatus: MemberStatus = "hiatus"; // 休業中
/**
 * PenlightPair holds the two penlight colors assigned to a member.
 */
export interface PenlightPair {
  left_color_id: ID; // col_... (Left hand / Color 1)
  right_color_id: ID; // col_... (Right hand / Color 2)
  ordered: boolean; // true if position matters, false if symmetric
}
/**
 * Member represents an idol member.
 * Natural keys (names) are never used as identifiers to prevent collisions on homonyms or name changes.
 */
export interface Member {
  id: ID; // mem_... (UUID v7 immutable surrogate key)
  group_id: ID; // grp_...
  family_name: string; // e.g. "加藤"
  given_name: string; // e.g. "史帆"
  family_name_kana: string; // e.g. "かとう"
  given_name_kana: string; // e.g. "しほ"
  generation: number /* int */; // e.g. 1 (1期生)
  status: MemberStatus; // active, graduated, hiatus
  penlight: PenlightPair; // Assigned penlight colors
  image_key: string; // Immutable image filename: e.g. "mem_<uuidv7>.webp"
  joined_at?: string; // Optional joining date
  graduated_at?: string; // Optional graduation date
  created_at: string;
  updated_at: string;
}

//////////
// source: quiz.go

/**
 * QuizOption represents one of the choices in a 4-choice penlight quiz.
 */
export interface QuizOption {
  member_id: ID;
  member_name: string;
  generation: number /* int */;
  penlight: PenlightPair;
  left_hex: string;
  right_hex: string;
  left_name: string;
  right_name: string;
  is_correct: boolean;
}
/**
 * QuizQuestion represents a 4-choice penlight quiz question.
 */
export interface QuizQuestion {
  id: ID; // quiz_... (UUID v7)
  target_member_id: ID; // mem_...
  target_member: Member;
  options: QuizOption[]; // Exactly 4 options
  correct_index: number /* int */; // 0-3
  generated_at: string;
}

//////////
// source: repository.go

/**
 * Repository defines data access operations required by the domain and HTTP handlers.
 * Following ADR-0004 and ADR-0017, this interface uses only Go standard library and
 * model package types to preserve zero external dependencies in the model layer.
 */
export type Repository = any;

//////////
// source: user.go

/**
 * User represents an authenticated or registered user.
 */
export interface User {
  id: ID; // usr_<uuidv7>
  google_sub?: string; // Google OIDC unique subject ID
  email?: string; // Google account email address
  display_name: string; // User public display name
  avatar_url: string; // Avatar image URL
  created_at: string;
  last_login_at: string;
}
