apiVersion: v1
kind: Secret
metadata:
  name: penlight-secret
  namespace: penlight
type: Opaque
stringData:
  # 32 bytes or more random string for cookie session signature (Ref: ADR-0015)
  SESSION_SECRET: "generate-via-openssl-rand-base64-32"
