-- Generated by scripts/build_seed.go from seeds/data/*.json
-- Master Data: Groups, Colors, Members, MemberImages, MasterVersions

INSERT OR IGNORE INTO groups (id, name, short_name, slug, theme_color_hex, display_order, is_active, created_at, updated_at)
VALUES ('grp_e6722901acc15ce2af3dacee3a83840c', '日向坂46', '日向坂', 'hinatazaka46', '#7CC7E8', 1, 1, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO groups (id, name, short_name, slug, theme_color_hex, display_order, is_active, created_at, updated_at)
VALUES ('grp_92629918b190528ab9ea941cd2e425f2', '櫻坂46', '櫻坂', 'sakurazaka46', '#F19DB5', 2, 1, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');

-- Official Penlight Colors
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_0f4a27244fdf510f8d7693b6f9392e3d', 'grp_e6722901acc15ce2af3dacee3a83840c', 'パステルブルー', '#09B8FF', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_4f3b1b7030ea5988951210c2472a107c', 'grp_e6722901acc15ce2af3dacee3a83840c', 'エメラルドグリーン', '#7AEA9F', 1, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_c26b71516fc255c092b8219fdca71cff', 'grp_e6722901acc15ce2af3dacee3a83840c', 'グリーン', '#02BDD6', 2, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_3cb2538786e6515e8bd1c6269b53d8e4', 'grp_e6722901acc15ce2af3dacee3a83840c', 'パールグリーン', '#72FF66', 3, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_fddfa593256d539aaeaa56a56501036c', 'grp_e6722901acc15ce2af3dacee3a83840c', 'ライトグリーン', '#D3FF64', 4, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_7788241b1592544092e9a5e5607ed64f', 'grp_e6722901acc15ce2af3dacee3a83840c', 'イエロー', '#FFF764', 5, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_f546c475f62853838cd7527e49a48f5e', 'grp_e6722901acc15ce2af3dacee3a83840c', 'オレンジ', '#FFAB09', 6, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_67e35b5f6e83555e84caedd87057eb12', 'grp_e6722901acc15ce2af3dacee3a83840c', 'レッド', '#FF1818', 7, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_1435c4981994548bb842ef227defb786', 'grp_e6722901acc15ce2af3dacee3a83840c', 'ホワイト', '#F5F5F5', 8, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_300e79231fd95edaab4d85033a1ba80e', 'grp_e6722901acc15ce2af3dacee3a83840c', 'サクラピンク', '#FF9AFD', 9, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_cc3e50e4389256d981cc9584109e5582', 'grp_e6722901acc15ce2af3dacee3a83840c', 'ピンク', '#FF18F6', 10, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_39bd89c979e75019aa2cc425d87b627a', 'grp_e6722901acc15ce2af3dacee3a83840c', 'パッションピンク', '#FF0988', 11, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_d94c1d31357d5c799aae0afe2481d356', 'grp_e6722901acc15ce2af3dacee3a83840c', 'バイオレット', '#C029DF', 12, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_a108b7059664526bb8805f64a3decf7f', 'grp_e6722901acc15ce2af3dacee3a83840c', 'パープル', '#9462D2', 13, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_b7eaef29bc315b5383a572cd77e9a48f', 'grp_e6722901acc15ce2af3dacee3a83840c', 'ブルー', '#1D72FE', 14, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_7c98f5489b3253e68a834ff2b2f54bba', 'grp_92629918b190528ab9ea941cd2e425f2', 'ホワイト', '#FFFFFF', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_58beea4b0fcf54f39debdb8dc08a788d', 'grp_92629918b190528ab9ea941cd2e425f2', 'サクラピンク', '#F9DDEC', 1, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_ef16cc72c68a5f37b0e1de514356d205', 'grp_92629918b190528ab9ea941cd2e425f2', 'グリーン', '#76FD4D', 2, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_25dddd3002ee511aaa393bece18c807e', 'grp_92629918b190528ab9ea941cd2e425f2', 'イエロー', '#FFFF54', 3, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_ca6ecff6d4c65d1c87571c5c7e13d4c1', 'grp_92629918b190528ab9ea941cd2e425f2', 'レッド', '#E73323', 4, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_e3452f29e6e1528a94a8d21f2b1bfcce', 'grp_92629918b190528ab9ea941cd2e425f2', 'パステルブルー', '#74BAE4', 5, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_3f3855999d3b5f31817e36ceee850eb9', 'grp_92629918b190528ab9ea941cd2e425f2', 'パープル', '#8E1BF9', 6, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_1505a540342b58efb1aa96c715a06c2e', 'grp_92629918b190528ab9ea941cd2e425f2', 'ピンク', '#EA33A2', 7, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_adfd2542f6125729be52506ccc9ba9a7', 'grp_92629918b190528ab9ea941cd2e425f2', 'エメラルドグリーン', '#4BA66E', 8, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_e8b1b12a274e540490af6852b578c9ec', 'grp_92629918b190528ab9ea941cd2e425f2', 'ライトグリーン', '#A7EA9B', 9, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_f764f14f2f985512845f27a266d0f17d', 'grp_92629918b190528ab9ea941cd2e425f2', 'バイオレット', '#AD24EF', 10, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_57b41d6ac5d255f1a18eeb6a854d7548', 'grp_92629918b190528ab9ea941cd2e425f2', 'パールグリーン', '#BEDBC3', 11, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_b37885f24ff15d4f9ae76f412dc7fcd2', 'grp_92629918b190528ab9ea941cd2e425f2', 'パッションピンク', '#EC34F7', 12, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_defa1cf2f1d25339b617b924a03f77b8', 'grp_92629918b190528ab9ea941cd2e425f2', 'オレンジ', '#F19E38', 13, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_8b2d93c75ddc5218b21e0dcabb1b59d7', 'grp_92629918b190528ab9ea941cd2e425f2', 'ブルー', '#0000F1', 14, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');

-- Idol Members
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_7dfb7abe142b516d914cb16b4b1526c5', 'grp_e6722901acc15ce2af3dacee3a83840c', '上村', 'ひなの', 'かみむら', 'ひなの', 3, 'active', 'col_4f3b1b7030ea5988951210c2472a107c', 'col_67e35b5f6e83555e84caedd87057eb12', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_b8aed4b172365711b1600ea1794c711b', 'grp_e6722901acc15ce2af3dacee3a83840c', '下田', '衣珠季', 'しもだ', 'いずき', 5, 'active', 'col_0f4a27244fdf510f8d7693b6f9392e3d', 'col_4f3b1b7030ea5988951210c2472a107c', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_79623099c3c35bd69b2f88b24d3dad38', 'grp_e6722901acc15ce2af3dacee3a83840c', '丹生', '明里', 'にぶ', 'あかり', 2, 'graduated', 'col_f546c475f62853838cd7527e49a48f5e', 'col_f546c475f62853838cd7527e49a48f5e', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_8fc76fc0b89951cc9fe0b4d28e2dac0c', 'grp_e6722901acc15ce2af3dacee3a83840c', '佐々木', '久美', 'ささき', 'くみ', 1, 'graduated', 'col_0f4a27244fdf510f8d7693b6f9392e3d', 'col_a108b7059664526bb8805f64a3decf7f', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_aefffdf4f6905c66b5a11158cbf4a242', 'grp_e6722901acc15ce2af3dacee3a83840c', '佐々木', '美玲', 'ささき', 'みれい', 1, 'graduated', 'col_7788241b1592544092e9a5e5607ed64f', 'col_7788241b1592544092e9a5e5607ed64f', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_fa28747d4e06546ebac146cf9f946ec5', 'grp_e6722901acc15ce2af3dacee3a83840c', '佐藤', '優羽', 'さとう', 'ゆう', 5, 'active', 'col_4f3b1b7030ea5988951210c2472a107c', 'col_4f3b1b7030ea5988951210c2472a107c', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_194f683faca85e43bcf38b859d845b6c', 'grp_e6722901acc15ce2af3dacee3a83840c', '加藤', '史帆', 'かとう', 'しほ', 1, 'graduated', 'col_b7eaef29bc315b5383a572cd77e9a48f', 'col_b7eaef29bc315b5383a572cd77e9a48f', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_6af22f9136a85bfe98ba4ac3b59fa430', 'grp_e6722901acc15ce2af3dacee3a83840c', '坂井', '新奈', 'さかい', 'にいな', 5, 'active', 'col_1435c4981994548bb842ef227defb786', 'col_1435c4981994548bb842ef227defb786', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_9dc9d92a001e57c58072ae318df0ecdd', 'grp_e6722901acc15ce2af3dacee3a83840c', '大田', '美月', 'おおた', 'みづき', 5, 'active', 'col_300e79231fd95edaab4d85033a1ba80e', 'col_cc3e50e4389256d981cc9584109e5582', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_7fbd1b67056f567795162f8c614a9b8f', 'grp_e6722901acc15ce2af3dacee3a83840c', '大野', '愛実', 'おおの', 'まなみ', 5, 'active', 'col_67e35b5f6e83555e84caedd87057eb12', 'col_67e35b5f6e83555e84caedd87057eb12', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_da56e038da335909bceca8f1ff77a539', 'grp_e6722901acc15ce2af3dacee3a83840c', '宮地', 'すみれ', 'みやち', 'すみれ', 4, 'active', 'col_d94c1d31357d5c799aae0afe2481d356', 'col_67e35b5f6e83555e84caedd87057eb12', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_be84efb349505cdb96ea0f3de6bdea07', 'grp_e6722901acc15ce2af3dacee3a83840c', '富田', '鈴花', 'とみた', 'すずか', 2, 'active', 'col_a108b7059664526bb8805f64a3decf7f', 'col_a108b7059664526bb8805f64a3decf7f', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_3ce56f5368fc51ccbcaff43ba2678e14', 'grp_e6722901acc15ce2af3dacee3a83840c', '小坂', '菜緒', 'こさか', 'なお', 2, 'active', 'col_1435c4981994548bb842ef227defb786', 'col_d94c1d31357d5c799aae0afe2481d356', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_ee9252bc92565c8987249c1705d54b81', 'grp_e6722901acc15ce2af3dacee3a83840c', '小西', '夏菜実', 'こにし', 'ななみ', 4, 'active', 'col_a108b7059664526bb8805f64a3decf7f', 'col_b7eaef29bc315b5383a572cd77e9a48f', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_affb4bacb0d75f3cae144021cc179d3d', 'grp_e6722901acc15ce2af3dacee3a83840c', '山下', '葉留花', 'やました', 'はるか', 4, 'active', 'col_1435c4981994548bb842ef227defb786', 'col_4f3b1b7030ea5988951210c2472a107c', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_f4226763e6c9552a9c387d92c0fdfe30', 'grp_e6722901acc15ce2af3dacee3a83840c', '山口', '陽世', 'やまぐち', 'はるよ', 3, 'active', 'col_3cb2538786e6515e8bd1c6269b53d8e4', 'col_7788241b1592544092e9a5e5607ed64f', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_c72c2fb7bb7d5bd897c9062cb17176fb', 'grp_e6722901acc15ce2af3dacee3a83840c', '平尾', '帆夏', 'ひらお', 'ほのか', 4, 'active', 'col_0f4a27244fdf510f8d7693b6f9392e3d', 'col_f546c475f62853838cd7527e49a48f5e', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_bc4804c468b25fa89cc1e568e76203eb', 'grp_e6722901acc15ce2af3dacee3a83840c', '平岡', '海月', 'ひらおか', 'みつき', 4, 'active', 'col_b7eaef29bc315b5383a572cd77e9a48f', 'col_7788241b1592544092e9a5e5607ed64f', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_e0f4fe5b5493518b891bcce77fe308f3', 'grp_e6722901acc15ce2af3dacee3a83840c', '東村', '芽依', 'ひがしむら', 'めい', 1, 'graduated', 'col_300e79231fd95edaab4d85033a1ba80e', 'col_300e79231fd95edaab4d85033a1ba80e', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_e44f49a59156551cb9f7fcd91d24faa1', 'grp_e6722901acc15ce2af3dacee3a83840c', '松尾', '桜', 'まつお', 'さくら', 5, 'active', 'col_300e79231fd95edaab4d85033a1ba80e', 'col_1435c4981994548bb842ef227defb786', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_002a63d1dd7556b788df1ca67347dffc', 'grp_e6722901acc15ce2af3dacee3a83840c', '松田', '好花', 'まつだ', 'このか', 2, 'active', 'col_3cb2538786e6515e8bd1c6269b53d8e4', 'col_300e79231fd95edaab4d85033a1ba80e', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_5ec3d7cd9b5352b5b485607d96c791f1', 'grp_e6722901acc15ce2af3dacee3a83840c', '森本', '茉莉', 'もりもと', 'まりぃ', 3, 'active', 'col_f546c475f62853838cd7527e49a48f5e', 'col_b7eaef29bc315b5383a572cd77e9a48f', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_93989e0003815378bcef9beab6a6417b', 'grp_e6722901acc15ce2af3dacee3a83840c', '正源司', '陽子', 'しょうげんじ', 'ようこ', 4, 'active', 'col_f546c475f62853838cd7527e49a48f5e', 'col_67e35b5f6e83555e84caedd87057eb12', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_dbedef91333c5dbe958d62c5c9f1e95d', 'grp_e6722901acc15ce2af3dacee3a83840c', '河田', '陽菜', 'かわた', 'ひな', 2, 'active', 'col_7788241b1592544092e9a5e5607ed64f', 'col_300e79231fd95edaab4d85033a1ba80e', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_ed3cee789f825b3d91c043676602d58e', 'grp_e6722901acc15ce2af3dacee3a83840c', '清水', '理央', 'しみず', 'りお', 4, 'active', 'col_0f4a27244fdf510f8d7693b6f9392e3d', 'col_cc3e50e4389256d981cc9584109e5582', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_9719a28cade6554086b6c35810a5997a', 'grp_e6722901acc15ce2af3dacee3a83840c', '渡辺', '莉奈', 'わたなべ', 'りな', 4, 'active', 'col_b7eaef29bc315b5383a572cd77e9a48f', 'col_1435c4981994548bb842ef227defb786', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_42d807c188dc5d65adba6fa5676f5221', 'grp_e6722901acc15ce2af3dacee3a83840c', '濱岸', 'ひより', 'はまぎし', 'ひより', 2, 'graduated', 'col_1435c4981994548bb842ef227defb786', 'col_f546c475f62853838cd7527e49a48f5e', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_a203dc50e87850f9ab52f0edb6aeacdc', 'grp_e6722901acc15ce2af3dacee3a83840c', '片山', '紗希', 'かたやま', 'さき', 5, 'active', 'col_0f4a27244fdf510f8d7693b6f9392e3d', 'col_0f4a27244fdf510f8d7693b6f9392e3d', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_f6d14207570e54ceb95a464dae0d760c', 'grp_e6722901acc15ce2af3dacee3a83840c', '石塚', '瑶季', 'いしづか', 'たまき', 4, 'active', 'col_300e79231fd95edaab4d85033a1ba80e', 'col_f546c475f62853838cd7527e49a48f5e', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_46ba7524619856c58dd99f91ce69b6a5', 'grp_e6722901acc15ce2af3dacee3a83840c', '竹内', '希来里', 'たけうち', 'きらり', 4, 'active', 'col_7788241b1592544092e9a5e5607ed64f', 'col_67e35b5f6e83555e84caedd87057eb12', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_e1feb6f0e02e5cdf932f32333b163411', 'grp_e6722901acc15ce2af3dacee3a83840c', '蔵盛', '妃那乃', 'くらもり', 'ひなの', 5, 'active', 'col_300e79231fd95edaab4d85033a1ba80e', 'col_67e35b5f6e83555e84caedd87057eb12', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_6e656285c7ba56b1accd34800f77eab6', 'grp_e6722901acc15ce2af3dacee3a83840c', '藤嶌', '果歩', 'ふじしま', 'かほ', 4, 'active', 'col_300e79231fd95edaab4d85033a1ba80e', 'col_b7eaef29bc315b5383a572cd77e9a48f', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_9fbea31ccf92550aa5da325c17d09c64', 'grp_e6722901acc15ce2af3dacee3a83840c', '金村', '美玖', 'かねむら', 'みく', 2, 'active', 'col_0f4a27244fdf510f8d7693b6f9392e3d', 'col_7788241b1592544092e9a5e5607ed64f', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_e8a3cef052b15f28a23b5a6eb84dc99d', 'grp_e6722901acc15ce2af3dacee3a83840c', '高井', '俐香', 'たかい', 'りか', 5, 'active', 'col_a108b7059664526bb8805f64a3decf7f', 'col_7788241b1592544092e9a5e5607ed64f', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_2098487fb2b45b129414de6e61808ec3', 'grp_e6722901acc15ce2af3dacee3a83840c', '高本', '彩花', 'たかもと', 'あやか', 1, 'graduated', 'col_1435c4981994548bb842ef227defb786', 'col_4f3b1b7030ea5988951210c2472a107c', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_6c4b735992ef5962bf0b3aff3369675e', 'grp_e6722901acc15ce2af3dacee3a83840c', '高瀬', '愛奈', 'たかせ', 'まな', 1, 'graduated', 'col_1435c4981994548bb842ef227defb786', 'col_cc3e50e4389256d981cc9584109e5582', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_2bfae489f3d855a29a6f892a5ddbe65a', 'grp_e6722901acc15ce2af3dacee3a83840c', '髙橋', '未来虹', 'たかはし', 'みくに', 3, 'active', 'col_c26b71516fc255c092b8219fdca71cff', 'col_a108b7059664526bb8805f64a3decf7f', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_7d4191c0d176566b9af06261ef10e653', 'grp_e6722901acc15ce2af3dacee3a83840c', '鶴崎', '仁香', 'つるさき', 'にこ', 5, 'active', 'col_7788241b1592544092e9a5e5607ed64f', 'col_f546c475f62853838cd7527e49a48f5e', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_557bdbe582b65aaa8bda577d6b8eaf0a', 'grp_e6722901acc15ce2af3dacee3a83840c', '齊藤', '京子', 'さいとう', 'きょうこ', 1, 'graduated', 'col_1435c4981994548bb842ef227defb786', 'col_1435c4981994548bb842ef227defb786', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_7550f1fb98455b3d908d3e1438d08cbb', 'grp_92629918b190528ab9ea941cd2e425f2', '中嶋', '優月', 'なかしま', 'ゆづき', 3, 'active', 'col_1505a540342b58efb1aa96c715a06c2e', 'col_1505a540342b58efb1aa96c715a06c2e', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_d38196cf0669533c9955bb5cbaffa794', 'grp_92629918b190528ab9ea941cd2e425f2', '中川', '智尋', 'なかがわ', 'ちひろ', 4, 'active', 'col_25dddd3002ee511aaa393bece18c807e', 'col_f764f14f2f985512845f27a266d0f17d', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_77120098dfd1559bb76b0ac075274c71', 'grp_92629918b190528ab9ea941cd2e425f2', '井上', '梨名', 'いのうえ', 'りな', 2, 'active', 'col_8b2d93c75ddc5218b21e0dcabb1b59d7', 'col_8b2d93c75ddc5218b21e0dcabb1b59d7', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_8d052fe65505563697db724e25831609', 'grp_92629918b190528ab9ea941cd2e425f2', '佐藤', '愛桜', 'さとう', 'ねお', 4, 'active', 'col_58beea4b0fcf54f39debdb8dc08a788d', 'col_e3452f29e6e1528a94a8d21f2b1bfcce', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_c60767d6b3995b9cbec82db107c45e77', 'grp_92629918b190528ab9ea941cd2e425f2', '勝又', '春', 'かつまた', 'はる', 4, 'active', 'col_58beea4b0fcf54f39debdb8dc08a788d', 'col_ca6ecff6d4c65d1c87571c5c7e13d4c1', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_0123417027f2515792cea1b774422504', 'grp_92629918b190528ab9ea941cd2e425f2', '向井', '純葉', 'むかい', 'いとは', 3, 'active', 'col_e3452f29e6e1528a94a8d21f2b1bfcce', 'col_adfd2542f6125729be52506ccc9ba9a7', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_17f94a6f6a4f55ddb12ef3e937951061', 'grp_92629918b190528ab9ea941cd2e425f2', '増本', '綺良', 'ますもと', 'きら', 2, 'active', 'col_defa1cf2f1d25339b617b924a03f77b8', 'col_defa1cf2f1d25339b617b924a03f77b8', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_fab118ced9865acd981e663ed8ceb7c9', 'grp_92629918b190528ab9ea941cd2e425f2', '大園', '玲', 'おおぞの', 'れい', 2, 'active', 'col_f764f14f2f985512845f27a266d0f17d', 'col_f764f14f2f985512845f27a266d0f17d', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_2d809d417aaf5fed96486a56c24879be', 'grp_92629918b190528ab9ea941cd2e425f2', '大沼', '晶保', 'おおぬま', 'あきほ', 2, 'active', 'col_25dddd3002ee511aaa393bece18c807e', 'col_e3452f29e6e1528a94a8d21f2b1bfcce', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_0691924b45ba537eb8a739a52122a040', 'grp_92629918b190528ab9ea941cd2e425f2', '守屋', '麗奈', 'もりや', 'れな', 2, 'active', 'col_25dddd3002ee511aaa393bece18c807e', 'col_1505a540342b58efb1aa96c715a06c2e', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_30c987b03bf75afab9b676f2f5d7d761', 'grp_92629918b190528ab9ea941cd2e425f2', '小島', '凪紗', 'こじま', 'なぎさ', 3, 'active', 'col_e3452f29e6e1528a94a8d21f2b1bfcce', 'col_defa1cf2f1d25339b617b924a03f77b8', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_1e5f31505fcf562598eb6835d9cb7017', 'grp_92629918b190528ab9ea941cd2e425f2', '小池', '美波', 'こいけ', 'みなみ', 1, 'graduated', 'col_7c98f5489b3253e68a834ff2b2f54bba', 'col_58beea4b0fcf54f39debdb8dc08a788d', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_18f81f86103e530c83029797f5ddef53', 'grp_92629918b190528ab9ea941cd2e425f2', '小田倉', '麗奈', 'おだくら', 'れいな', 3, 'active', 'col_7c98f5489b3253e68a834ff2b2f54bba', 'col_58beea4b0fcf54f39debdb8dc08a788d', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_cbf48a1ef0ba55838b20daec8ac4a584', 'grp_92629918b190528ab9ea941cd2e425f2', '山下', '瞳月', 'やました', 'しづき', 3, 'active', 'col_ca6ecff6d4c65d1c87571c5c7e13d4c1', 'col_e3452f29e6e1528a94a8d21f2b1bfcce', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_27a7aab4d3d75ccda67f8d3a9537be63', 'grp_92629918b190528ab9ea941cd2e425f2', '山川', '宇衣', 'やまかわ', 'うい', 4, 'active', 'col_7c98f5489b3253e68a834ff2b2f54bba', 'col_e3452f29e6e1528a94a8d21f2b1bfcce', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_a5ff8617344859cc83f0283976298c25', 'grp_92629918b190528ab9ea941cd2e425f2', '山田', '桃実', 'やまだ', 'ももみ', 4, 'active', 'col_e3452f29e6e1528a94a8d21f2b1bfcce', 'col_f764f14f2f985512845f27a266d0f17d', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_4682dd06532d525eada319118369d3a1', 'grp_92629918b190528ab9ea941cd2e425f2', '山﨑', '天', 'やまさき', 'てん', 2, 'active', 'col_7c98f5489b3253e68a834ff2b2f54bba', 'col_ef16cc72c68a5f37b0e1de514356d205', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_832e5906aa2350ccac5dfa4d9cf80c6e', 'grp_92629918b190528ab9ea941cd2e425f2', '幸阪', '茉里乃', 'こうさか', 'まりの', 2, 'active', 'col_58beea4b0fcf54f39debdb8dc08a788d', 'col_57b41d6ac5d255f1a18eeb6a854d7548', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_a18f6a3db23358e3bc926a160cde54e9', 'grp_92629918b190528ab9ea941cd2e425f2', '村井', '優', 'むらい', 'ゆう', 3, 'active', 'col_3f3855999d3b5f31817e36ceee850eb9', 'col_8b2d93c75ddc5218b21e0dcabb1b59d7', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_72fcd84ec1545dd4b22c1a3feae5343d', 'grp_92629918b190528ab9ea941cd2e425f2', '村山', '美羽', 'むらやま', 'みう', 3, 'active', 'col_3f3855999d3b5f31817e36ceee850eb9', 'col_8b2d93c75ddc5218b21e0dcabb1b59d7', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_22ece5b62004540eb1070bd9f76817a6', 'grp_92629918b190528ab9ea941cd2e425f2', '松本', '和子', 'まつもと', 'わこ', 4, 'active', 'col_7c98f5489b3253e68a834ff2b2f54bba', 'col_adfd2542f6125729be52506ccc9ba9a7', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_ad244c328d655784b06e124a84502c20', 'grp_92629918b190528ab9ea941cd2e425f2', '松田', '里奈', 'まつだ', 'りな', 2, 'active', 'col_ef16cc72c68a5f37b0e1de514356d205', 'col_25dddd3002ee511aaa393bece18c807e', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_02371e75dd1a54329cf6529e614f323f', 'grp_92629918b190528ab9ea941cd2e425f2', '森田', 'ひかる', 'もりた', 'ひかる', 2, 'active', 'col_ca6ecff6d4c65d1c87571c5c7e13d4c1', 'col_8b2d93c75ddc5218b21e0dcabb1b59d7', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_ef141612bb7050259ad94fbe98990b93', 'grp_92629918b190528ab9ea941cd2e425f2', '武元', '唯衣', 'たけもと', 'ゆい', 2, 'active', 'col_b37885f24ff15d4f9ae76f412dc7fcd2', 'col_8b2d93c75ddc5218b21e0dcabb1b59d7', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_652418691e795202b9f2aff5fae6477b', 'grp_92629918b190528ab9ea941cd2e425f2', '浅井', '恋乃未', 'あさい', 'このみ', 4, 'active', 'col_ca6ecff6d4c65d1c87571c5c7e13d4c1', 'col_adfd2542f6125729be52506ccc9ba9a7', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_9b900e3d9a815ea6a154d92799d08430', 'grp_92629918b190528ab9ea941cd2e425f2', '田村', '保乃', 'たむら', 'ほの', 2, 'active', 'col_e3452f29e6e1528a94a8d21f2b1bfcce', 'col_e3452f29e6e1528a94a8d21f2b1bfcce', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_564ba06a76b3502fbb951399a5c5d24e', 'grp_92629918b190528ab9ea941cd2e425f2', '的野', '美青', 'まとの', 'みお', 3, 'active', 'col_e3452f29e6e1528a94a8d21f2b1bfcce', 'col_8b2d93c75ddc5218b21e0dcabb1b59d7', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_f25d8752867a51e6b29c26170a1ddafd', 'grp_92629918b190528ab9ea941cd2e425f2', '目黒', '陽色', 'めぐろ', 'ひいろ', 4, 'active', 'col_58beea4b0fcf54f39debdb8dc08a788d', 'col_b37885f24ff15d4f9ae76f412dc7fcd2', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_d2a98fc47bd751ffb69f02300e05f9fc', 'grp_92629918b190528ab9ea941cd2e425f2', '石森', '璃花', 'いしもり', 'りか', 3, 'active', 'col_ef16cc72c68a5f37b0e1de514356d205', 'col_1505a540342b58efb1aa96c715a06c2e', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_eb9f507b74235d9ab3e1759a400becbb', 'grp_92629918b190528ab9ea941cd2e425f2', '稲熊', 'ひな', 'いなぐま', 'ひな', 4, 'active', 'col_adfd2542f6125729be52506ccc9ba9a7', 'col_defa1cf2f1d25339b617b924a03f77b8', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_e21c08bd18f45171bb92edaa956ba233', 'grp_92629918b190528ab9ea941cd2e425f2', '藤吉', '夏鈴', 'ふじよし', 'かりん', 2, 'active', 'col_7c98f5489b3253e68a834ff2b2f54bba', 'col_f764f14f2f985512845f27a266d0f17d', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_eecdf2042be9513bb8de51c027a463a3', 'grp_92629918b190528ab9ea941cd2e425f2', '谷口', '愛季', 'たにぐち', 'あいり', 3, 'active', 'col_ca6ecff6d4c65d1c87571c5c7e13d4c1', 'col_f764f14f2f985512845f27a266d0f17d', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_4de21332af30544e87c1d89bc21d01e1', 'grp_92629918b190528ab9ea941cd2e425f2', '遠藤', '光莉', 'えんどう', 'ひかり', 2, 'active', 'col_3f3855999d3b5f31817e36ceee850eb9', 'col_3f3855999d3b5f31817e36ceee850eb9', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_61023eeb30125bfdb2c2284d3c77b3d6', 'grp_92629918b190528ab9ea941cd2e425f2', '遠藤', '理子', 'えんどう', 'りこ', 3, 'active', 'col_58beea4b0fcf54f39debdb8dc08a788d', 'col_f764f14f2f985512845f27a266d0f17d', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');

-- Member Images (1:N, Ref: ADR-0021)
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_dc063594ccd454709b6d54ad66838c76', 'mem_7dfb7abe142b516d914cb16b4b1526c5', 'img_dc063594ccd454709b6d54ad66838c76.webp', '13th Single 制服', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_2bbea8559fd25c9bb6fb6dc560916693', 'mem_7dfb7abe142b516d914cb16b4b1526c5', 'img_2bbea8559fd25c9bb6fb6dc560916693.webp', '5回目のひな誕祭 個別マフラータオル', 0, 1, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_847a20ba1ae45b5390e2696db99c6dc4', 'mem_b8aed4b172365711b1600ea1794c711b', 'img_847a20ba1ae45b5390e2696db99c6dc4.webp', '5期生 新メンバー', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_96c2d679fda452c9bbb9a860d361eae1', 'mem_79623099c3c35bd69b2f88b24d3dad38', 'img_96c2d679fda452c9bbb9a860d361eae1.webp', '5回目のひな誕祭 個別マフラータオル', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_e47daec5db0751699f8281ae61064f91', 'mem_8fc76fc0b89951cc9fe0b4d28e2dac0c', 'img_e47daec5db0751699f8281ae61064f91.webp', '13th Single 制服', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_b7f8c802c8895bdcbbb998a841c0b09d', 'mem_8fc76fc0b89951cc9fe0b4d28e2dac0c', 'img_b7f8c802c8895bdcbbb998a841c0b09d.webp', '5回目のひな誕祭 個別マフラータオル', 0, 1, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_6a9df76f45085e43bc913335920a2a75', 'mem_aefffdf4f6905c66b5a11158cbf4a242', 'img_6a9df76f45085e43bc913335920a2a75.webp', '13th Single 制服', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_4c61b16e1f8f518cae2bcfb698c6c7dd', 'mem_aefffdf4f6905c66b5a11158cbf4a242', 'img_4c61b16e1f8f518cae2bcfb698c6c7dd.webp', '5回目のひな誕祭 個別マフラータオル', 0, 1, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_e6486950dcb352f9997964c948c63ecc', 'mem_fa28747d4e06546ebac146cf9f946ec5', 'img_e6486950dcb352f9997964c948c63ecc.webp', '5期生 新メンバー', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_4b57e50edbe6532b9272c5faa7d06dec', 'mem_194f683faca85e43bcf38b859d845b6c', 'img_4b57e50edbe6532b9272c5faa7d06dec.webp', '5回目のひな誕祭 個別マフラータオル', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_ad3d8ead8ff552ca9a97d379ae5610c7', 'mem_6af22f9136a85bfe98ba4ac3b59fa430', 'img_ad3d8ead8ff552ca9a97d379ae5610c7.webp', '5期生 新メンバー', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_7cd23f4f8e5653ff8b06405ab37626cf', 'mem_9dc9d92a001e57c58072ae318df0ecdd', 'img_7cd23f4f8e5653ff8b06405ab37626cf.webp', '5期生 新メンバー', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_46ad61b687505743b682fb11ed85b576', 'mem_7fbd1b67056f567795162f8c614a9b8f', 'img_46ad61b687505743b682fb11ed85b576.webp', '5期生 新メンバー', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_e1f74b2f2dd956ed9f48e66baf3daaf3', 'mem_da56e038da335909bceca8f1ff77a539', 'img_e1f74b2f2dd956ed9f48e66baf3daaf3.webp', '13th Single 制服', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_11b5418732615cbda2a656a941491cd4', 'mem_da56e038da335909bceca8f1ff77a539', 'img_11b5418732615cbda2a656a941491cd4.webp', '5回目のひな誕祭 個別マフラータオル', 0, 1, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_128124ef289051d8ac0d1c431d7e8b76', 'mem_be84efb349505cdb96ea0f3de6bdea07', 'img_128124ef289051d8ac0d1c431d7e8b76.webp', '13th Single 制服', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_c7f65a3bd09a570f9489debdb79e783d', 'mem_be84efb349505cdb96ea0f3de6bdea07', 'img_c7f65a3bd09a570f9489debdb79e783d.webp', '5回目のひな誕祭 個別マフラータオル', 0, 1, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_11e5867149a653f08e2ea1deb2eea0b0', 'mem_3ce56f5368fc51ccbcaff43ba2678e14', 'img_11e5867149a653f08e2ea1deb2eea0b0.webp', '13th Single 制服', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_bf5135ee783d5b778b3bc9ac4670405a', 'mem_3ce56f5368fc51ccbcaff43ba2678e14', 'img_bf5135ee783d5b778b3bc9ac4670405a.webp', '5回目のひな誕祭 個別マフラータオル', 0, 1, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_eea5304d2ad35697a3e2e39934217659', 'mem_ee9252bc92565c8987249c1705d54b81', 'img_eea5304d2ad35697a3e2e39934217659.webp', '13th Single 制服', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_7a5a64b23ae75add8f4b4e94c055d516', 'mem_ee9252bc92565c8987249c1705d54b81', 'img_7a5a64b23ae75add8f4b4e94c055d516.webp', '5回目のひな誕祭 個別マフラータオル', 0, 1, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_db042695dedf575ea063fbd48741313c', 'mem_affb4bacb0d75f3cae144021cc179d3d', 'img_db042695dedf575ea063fbd48741313c.webp', '13th Single 制服', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_8e9aa3dad4be5f0a9eedf1a9df160305', 'mem_affb4bacb0d75f3cae144021cc179d3d', 'img_8e9aa3dad4be5f0a9eedf1a9df160305.webp', '5回目のひな誕祭 個別マフラータオル', 0, 1, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_3a80562263a95d1f8246584438adc004', 'mem_f4226763e6c9552a9c387d92c0fdfe30', 'img_3a80562263a95d1f8246584438adc004.webp', '13th Single 制服', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_83b34dc93b9b5d4d9108475197782c85', 'mem_f4226763e6c9552a9c387d92c0fdfe30', 'img_83b34dc93b9b5d4d9108475197782c85.webp', '5回目のひな誕祭 個別マフラータオル', 0, 1, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_1398ae5d5a0b5e2eb1083da28f26b261', 'mem_c72c2fb7bb7d5bd897c9062cb17176fb', 'img_1398ae5d5a0b5e2eb1083da28f26b261.webp', '13th Single 制服', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_fa170e2121f15782bbb1c871bade0751', 'mem_c72c2fb7bb7d5bd897c9062cb17176fb', 'img_fa170e2121f15782bbb1c871bade0751.webp', '5回目のひな誕祭 個別マフラータオル', 0, 1, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_09e30eaf7303566a8a5bf2eeefddf048', 'mem_bc4804c468b25fa89cc1e568e76203eb', 'img_09e30eaf7303566a8a5bf2eeefddf048.webp', '13th Single 制服', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_1ac692a61b9550b49dcbb9b416b13be4', 'mem_bc4804c468b25fa89cc1e568e76203eb', 'img_1ac692a61b9550b49dcbb9b416b13be4.webp', '5回目のひな誕祭 個別マフラータオル', 0, 1, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_fc8eb2503f4c52b280195c77c1573d5e', 'mem_e0f4fe5b5493518b891bcce77fe308f3', 'img_fc8eb2503f4c52b280195c77c1573d5e.webp', '5回目のひな誕祭 個別マフラータオル', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_fee5f99c18ea530c80677ccee22880e9', 'mem_e44f49a59156551cb9f7fcd91d24faa1', 'img_fee5f99c18ea530c80677ccee22880e9.webp', '5期生 新メンバー', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_5e8b4187ced354978b711d8145fd8110', 'mem_002a63d1dd7556b788df1ca67347dffc', 'img_5e8b4187ced354978b711d8145fd8110.webp', '13th Single 制服', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_8f21f47f141557798df4a064b5e54366', 'mem_002a63d1dd7556b788df1ca67347dffc', 'img_8f21f47f141557798df4a064b5e54366.webp', '5回目のひな誕祭 個別マフラータオル', 0, 1, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_03cd25a8c657587eb2f6a1b1c3d0f735', 'mem_5ec3d7cd9b5352b5b485607d96c791f1', 'img_03cd25a8c657587eb2f6a1b1c3d0f735.webp', '13th Single 制服', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_6dbb50257d8857549327a3fbd5d35553', 'mem_5ec3d7cd9b5352b5b485607d96c791f1', 'img_6dbb50257d8857549327a3fbd5d35553.webp', '5回目のひな誕祭 個別マフラータオル', 0, 1, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_8d91a21dda67578abf99c1fc542f626a', 'mem_93989e0003815378bcef9beab6a6417b', 'img_8d91a21dda67578abf99c1fc542f626a.webp', '5回目のひな誕祭 個別マフラータオル', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_4de5514473695e94aac8c781f3ef5b43', 'mem_dbedef91333c5dbe958d62c5c9f1e95d', 'img_4de5514473695e94aac8c781f3ef5b43.webp', '13th Single 制服', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_3b20506ce9b05568a1dee6cf00283a16', 'mem_dbedef91333c5dbe958d62c5c9f1e95d', 'img_3b20506ce9b05568a1dee6cf00283a16.webp', '5回目のひな誕祭 個別マフラータオル', 0, 1, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_b2dae00b19145f469ba1d377dc99fa6d', 'mem_ed3cee789f825b3d91c043676602d58e', 'img_b2dae00b19145f469ba1d377dc99fa6d.webp', '13th Single 制服', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_2df95b7ad28853fdad80c695d820f199', 'mem_ed3cee789f825b3d91c043676602d58e', 'img_2df95b7ad28853fdad80c695d820f199.webp', '5回目のひな誕祭 個別マフラータオル', 0, 1, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_6659f3c82b235fd79bdaf33a2451a858', 'mem_9719a28cade6554086b6c35810a5997a', 'img_6659f3c82b235fd79bdaf33a2451a858.webp', '13th Single 制服', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_6cbdbfc72f5d557d9f7075b99ce5e26e', 'mem_42d807c188dc5d65adba6fa5676f5221', 'img_6cbdbfc72f5d557d9f7075b99ce5e26e.webp', '5回目のひな誕祭 個別マフラータオル', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_2e04c092d6ed56cabd8768c2dedd2665', 'mem_a203dc50e87850f9ab52f0edb6aeacdc', 'img_2e04c092d6ed56cabd8768c2dedd2665.webp', '5期生 新メンバー', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_fad119dad25a51e7acfcdf1a743fe338', 'mem_f6d14207570e54ceb95a464dae0d760c', 'img_fad119dad25a51e7acfcdf1a743fe338.webp', '13th Single 制服', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_b45ae3cdbcc752a492e0834502f2e80d', 'mem_f6d14207570e54ceb95a464dae0d760c', 'img_b45ae3cdbcc752a492e0834502f2e80d.webp', '5回目のひな誕祭 個別マフラータオル', 0, 1, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_007aea2773945aa0b3f616a3a04c869d', 'mem_46ba7524619856c58dd99f91ce69b6a5', 'img_007aea2773945aa0b3f616a3a04c869d.webp', '13th Single 制服', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_6e6b8758336a5d97aea8cb6ede41d612', 'mem_46ba7524619856c58dd99f91ce69b6a5', 'img_6e6b8758336a5d97aea8cb6ede41d612.webp', '5回目のひな誕祭 個別マフラータオル', 0, 1, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_8c601e09dba25407bd557a20e5c7a956', 'mem_e1feb6f0e02e5cdf932f32333b163411', 'img_8c601e09dba25407bd557a20e5c7a956.webp', '5期生 新メンバー', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_318d12668c8f5a4eac18c408da34c8a3', 'mem_6e656285c7ba56b1accd34800f77eab6', 'img_318d12668c8f5a4eac18c408da34c8a3.webp', '13th Single 制服', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_07aee6bc12f9580dab5a12418264df3f', 'mem_9fbea31ccf92550aa5da325c17d09c64', 'img_07aee6bc12f9580dab5a12418264df3f.webp', '13th Single 制服', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_b50a0d94755f5b52b12fcc458a4445e6', 'mem_9fbea31ccf92550aa5da325c17d09c64', 'img_b50a0d94755f5b52b12fcc458a4445e6.webp', '5回目のひな誕祭 個別マフラータオル', 0, 1, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_564a605068585d72bcdb3608d7e7a1e2', 'mem_e8a3cef052b15f28a23b5a6eb84dc99d', 'img_564a605068585d72bcdb3608d7e7a1e2.webp', '5期生 新メンバー', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_a8e9f6db42915d1a8a7026afde47793a', 'mem_2098487fb2b45b129414de6e61808ec3', 'img_a8e9f6db42915d1a8a7026afde47793a.webp', '5回目のひな誕祭 個別マフラータオル', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_590214468c4c5cf198afeb3d453b50e6', 'mem_6c4b735992ef5962bf0b3aff3369675e', 'img_590214468c4c5cf198afeb3d453b50e6.webp', '13th Single 制服', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_d7fe014f255f5f36b0d11093c71f115e', 'mem_6c4b735992ef5962bf0b3aff3369675e', 'img_d7fe014f255f5f36b0d11093c71f115e.webp', '5回目のひな誕祭 個別マフラータオル', 0, 1, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_c19ab9d6a92e5391bc4e6e58a07d0062', 'mem_2bfae489f3d855a29a6f892a5ddbe65a', 'img_c19ab9d6a92e5391bc4e6e58a07d0062.webp', '5回目のひな誕祭 個別マフラータオル', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_eb3e8032a1e55308b9f8f8e3bdc8a336', 'mem_7d4191c0d176566b9af06261ef10e653', 'img_eb3e8032a1e55308b9f8f8e3bdc8a336.webp', '5期生 新メンバー', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_70d464ba4e765cf5880c7b98c4cdb7fc', 'mem_557bdbe582b65aaa8bda577d6b8eaf0a', 'img_70d464ba4e765cf5880c7b98c4cdb7fc.webp', '5回目のひな誕祭 個別マフラータオル', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_d759070645f85e7a9978708bbf578242', 'mem_7550f1fb98455b3d908d3e1438d08cbb', 'img_d759070645f85e7a9978708bbf578242.webp', '2nd Album アー写', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_87c1973487625091bdca1e6883ab1710', 'mem_d38196cf0669533c9955bb5cbaffa794', 'img_87c1973487625091bdca1e6883ab1710.webp', '4th ARENA TOUR 2024 個別マフラータオル', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_b44bedeef7705f839749e96ecf6c41ea', 'mem_77120098dfd1559bb76b0ac075274c71', 'img_b44bedeef7705f839749e96ecf6c41ea.webp', '2nd Album アー写', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_dd4739a5c9a85f44b966255c5d5f92fe', 'mem_8d052fe65505563697db724e25831609', 'img_dd4739a5c9a85f44b966255c5d5f92fe.webp', '4th ARENA TOUR 2024 個別マフラータオル', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_26fadd31f4c65b1189a15a504233d863', 'mem_c60767d6b3995b9cbec82db107c45e77', 'img_26fadd31f4c65b1189a15a504233d863.webp', '4th ARENA TOUR 2024 個別マフラータオル', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_541a5ebf110e50e4b22e1e7257618a82', 'mem_0123417027f2515792cea1b774422504', 'img_541a5ebf110e50e4b22e1e7257618a82.webp', '2nd Album アー写', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_4eb373567b525f4db2bd8ffafaca86e6', 'mem_17f94a6f6a4f55ddb12ef3e937951061', 'img_4eb373567b525f4db2bd8ffafaca86e6.webp', '2nd Album アー写', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_f38f54988427583e8f3832bff317ce6d', 'mem_fab118ced9865acd981e663ed8ceb7c9', 'img_f38f54988427583e8f3832bff317ce6d.webp', '2nd Album アー写', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_32866403cd7550509cc0995f3cf43fb2', 'mem_2d809d417aaf5fed96486a56c24879be', 'img_32866403cd7550509cc0995f3cf43fb2.webp', '2nd Album アー写', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_5244d6e03c925e528bb6a2ae3f781f58', 'mem_0691924b45ba537eb8a739a52122a040', 'img_5244d6e03c925e528bb6a2ae3f781f58.webp', '2nd Album アー写', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_02e13dff52d05b0b98f19ba07d9f3b27', 'mem_30c987b03bf75afab9b676f2f5d7d761', 'img_02e13dff52d05b0b98f19ba07d9f3b27.webp', '2nd Album アー写', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_9cf748e54902571192d09b93407b5e42', 'mem_1e5f31505fcf562598eb6835d9cb7017', 'img_9cf748e54902571192d09b93407b5e42.webp', '2nd Album アー写', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_f9f7da736e7d53a3a8d8e7550ea76d55', 'mem_18f81f86103e530c83029797f5ddef53', 'img_f9f7da736e7d53a3a8d8e7550ea76d55.webp', '2nd Album アー写', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_b502fca6369753b9b66f255567ab7b46', 'mem_cbf48a1ef0ba55838b20daec8ac4a584', 'img_b502fca6369753b9b66f255567ab7b46.webp', '2nd Album アー写', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_4f2100b4dba35c94a1f089defbfd7129', 'mem_27a7aab4d3d75ccda67f8d3a9537be63', 'img_4f2100b4dba35c94a1f089defbfd7129.webp', '4th ARENA TOUR 2024 個別マフラータオル', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_1099ac1663b4527ebf6f8dc4a7f9e330', 'mem_a5ff8617344859cc83f0283976298c25', 'img_1099ac1663b4527ebf6f8dc4a7f9e330.webp', '4th ARENA TOUR 2024 個別マフラータオル', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_0620b8de365e5549a986a746506f6960', 'mem_4682dd06532d525eada319118369d3a1', 'img_0620b8de365e5549a986a746506f6960.webp', '2nd Album アー写', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_1e8de4f19f86520a8ae1bcf58bd0b88b', 'mem_832e5906aa2350ccac5dfa4d9cf80c6e', 'img_1e8de4f19f86520a8ae1bcf58bd0b88b.webp', '2nd Album アー写', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_dc04450ac9f25c0188b6dddbc7576802', 'mem_a18f6a3db23358e3bc926a160cde54e9', 'img_dc04450ac9f25c0188b6dddbc7576802.webp', '2nd Album アー写', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_721603e5c98e5b0cb562791547301797', 'mem_72fcd84ec1545dd4b22c1a3feae5343d', 'img_721603e5c98e5b0cb562791547301797.webp', '2nd Album アー写', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_6061fdee3c955623867dc12593996133', 'mem_22ece5b62004540eb1070bd9f76817a6', 'img_6061fdee3c955623867dc12593996133.webp', '4th ARENA TOUR 2024 個別マフラータオル', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_a55becdcb5f453daa8a1710b2ad22dc0', 'mem_ad244c328d655784b06e124a84502c20', 'img_a55becdcb5f453daa8a1710b2ad22dc0.webp', '2nd Album アー写', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_ee50d0075d4750119c16dc9917cf8079', 'mem_02371e75dd1a54329cf6529e614f323f', 'img_ee50d0075d4750119c16dc9917cf8079.webp', '2nd Album アー写', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_657d85c0b9ce5dd2b454de39711de786', 'mem_ef141612bb7050259ad94fbe98990b93', 'img_657d85c0b9ce5dd2b454de39711de786.webp', '2nd Album アー写', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_593c80572bab53b6bcf4b60c6522da79', 'mem_652418691e795202b9f2aff5fae6477b', 'img_593c80572bab53b6bcf4b60c6522da79.webp', '4th ARENA TOUR 2024 個別マフラータオル', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_6a9225e7684e5a0fbb7f778ee2dea7d9', 'mem_9b900e3d9a815ea6a154d92799d08430', 'img_6a9225e7684e5a0fbb7f778ee2dea7d9.webp', '2nd Album アー写', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_fc750bfbd8b15afb9a3bb8be814515a3', 'mem_564ba06a76b3502fbb951399a5c5d24e', 'img_fc750bfbd8b15afb9a3bb8be814515a3.webp', '2nd Album アー写', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_5216adf7edab5432856e190820665315', 'mem_f25d8752867a51e6b29c26170a1ddafd', 'img_5216adf7edab5432856e190820665315.webp', '4th ARENA TOUR 2024 個別マフラータオル', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_b6faf6856ab85be3a543d88de0e68639', 'mem_d2a98fc47bd751ffb69f02300e05f9fc', 'img_b6faf6856ab85be3a543d88de0e68639.webp', '2nd Album アー写', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_22d56b3319515904aad302654da18573', 'mem_eb9f507b74235d9ab3e1759a400becbb', 'img_22d56b3319515904aad302654da18573.webp', '4th ARENA TOUR 2024 個別マフラータオル', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_05d7562ebadb58a7a546dd17e91cb17b', 'mem_e21c08bd18f45171bb92edaa956ba233', 'img_05d7562ebadb58a7a546dd17e91cb17b.webp', '2nd Album アー写', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_017b099363a852c288111dce37991caf', 'mem_eecdf2042be9513bb8de51c027a463a3', 'img_017b099363a852c288111dce37991caf.webp', '2nd Album アー写', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_1b0b667db96756f78143f3f4b8e5c081', 'mem_4de21332af30544e87c1d89bc21d01e1', 'img_1b0b667db96756f78143f3f4b8e5c081.webp', '2nd Album アー写', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, image_key, title, is_primary, display_order, created_at, updated_at)
VALUES ('img_5a451440701c5ceb8ffba1887f253b54', 'mem_61023eeb30125bfdb2c2284d3c77b3d6', 'img_5a451440701c5ceb8ffba1887f253b54.webp', '2nd Album アー写', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');

-- Master Version (Ref: ADR-0021)
INSERT OR REPLACE INTO master_versions (id, version, updated_at)
VALUES ('current', '2026.10.04-1', '2026-10-04T00:00:00Z');
