-- Generated by scripts/build_seed.go from seeds/data/*.json
-- Master Data: Groups, Colors, PhotoTypes, Members, MemberImages, MasterVersions

INSERT OR IGNORE INTO groups (id, name, short_name, slug, theme_color_hex, display_order, is_active, created_at, updated_at)
VALUES ('grp_e6722901acc15ce2af3dacee3a83840c', '日向坂46', '日向坂', 'hinatazaka46', '#7CC7E8', 1, 1, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO groups (id, name, short_name, slug, theme_color_hex, display_order, is_active, created_at, updated_at)
VALUES ('grp_92629918b190528ab9ea941cd2e425f2', '櫻坂46', '櫻坂', 'sakurazaka46', '#F19DB5', 2, 1, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO groups (id, name, short_name, slug, theme_color_hex, display_order, is_active, created_at, updated_at)
VALUES ('grp_fb2466e223f1558ea71bf2d0ba4c7469', '乃木坂46', '乃木坂', 'nogizaka46', '#7E2682', 3, 1, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');

-- Official Penlight Colors
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_0f4a27244fdf510f8d7693b6f9392e3d', 'grp_e6722901acc15ce2af3dacee3a83840c', 'パステルブルー', '#09B8FF', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_4f3b1b7030ea5988951210c2472a107c', 'grp_e6722901acc15ce2af3dacee3a83840c', 'エメラルドグリーン', '#7AEA9F', 1, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_c26b71516fc255c092b8219fdca71cff', 'grp_e6722901acc15ce2af3dacee3a83840c', 'グリーン', '#02BDD6', 2, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_3cb2538786e6515e8bd1c6269b53d8e4', 'grp_e6722901acc15ce2af3dacee3a83840c', 'パールグリーン', '#72FF66', 3, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_fddfa593256d539aaeaa56a56501036c', 'grp_e6722901acc15ce2af3dacee3a83840c', 'ライトグリーン', '#D3FF64', 4, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_7788241b1592544092e9a5e5607ed64f', 'grp_e6722901acc15ce2af3dacee3a83840c', 'イエロー', '#FFF764', 5, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_f546c475f62853838cd7527e49a48f5e', 'grp_e6722901acc15ce2af3dacee3a83840c', 'オレンジ', '#FFAB09', 6, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_67e35b5f6e83555e84caedd87057eb12', 'grp_e6722901acc15ce2af3dacee3a83840c', 'レッド', '#FF1818', 7, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_1435c4981994548bb842ef227defb786', 'grp_e6722901acc15ce2af3dacee3a83840c', 'ホワイト', '#F5F5F5', 8, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_300e79231fd95edaab4d85033a1ba80e', 'grp_e6722901acc15ce2af3dacee3a83840c', 'サクラピンク', '#FF9AFD', 9, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_cc3e50e4389256d981cc9584109e5582', 'grp_e6722901acc15ce2af3dacee3a83840c', 'ピンク', '#FF18F6', 10, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_39bd89c979e75019aa2cc425d87b627a', 'grp_e6722901acc15ce2af3dacee3a83840c', 'パッションピンク', '#FF0988', 11, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_d94c1d31357d5c799aae0afe2481d356', 'grp_e6722901acc15ce2af3dacee3a83840c', 'バイオレット', '#C029DF', 12, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_a108b7059664526bb8805f64a3decf7f', 'grp_e6722901acc15ce2af3dacee3a83840c', 'パープル', '#9462D2', 13, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_b7eaef29bc315b5383a572cd77e9a48f', 'grp_e6722901acc15ce2af3dacee3a83840c', 'ブルー', '#1D72FE', 14, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_7c98f5489b3253e68a834ff2b2f54bba', 'grp_92629918b190528ab9ea941cd2e425f2', 'ホワイト', '#FFFFFF', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_58beea4b0fcf54f39debdb8dc08a788d', 'grp_92629918b190528ab9ea941cd2e425f2', 'サクラピンク', '#F9DDEC', 1, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_ef16cc72c68a5f37b0e1de514356d205', 'grp_92629918b190528ab9ea941cd2e425f2', 'グリーン', '#76FD4D', 2, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_25dddd3002ee511aaa393bece18c807e', 'grp_92629918b190528ab9ea941cd2e425f2', 'イエロー', '#FFFF54', 3, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_ca6ecff6d4c65d1c87571c5c7e13d4c1', 'grp_92629918b190528ab9ea941cd2e425f2', 'レッド', '#E73323', 4, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_e3452f29e6e1528a94a8d21f2b1bfcce', 'grp_92629918b190528ab9ea941cd2e425f2', 'パステルブルー', '#74BAE4', 5, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_3f3855999d3b5f31817e36ceee850eb9', 'grp_92629918b190528ab9ea941cd2e425f2', 'パープル', '#8E1BF9', 6, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_1505a540342b58efb1aa96c715a06c2e', 'grp_92629918b190528ab9ea941cd2e425f2', 'ピンク', '#EA33A2', 7, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_adfd2542f6125729be52506ccc9ba9a7', 'grp_92629918b190528ab9ea941cd2e425f2', 'エメラルドグリーン', '#4BA66E', 8, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_e8b1b12a274e540490af6852b578c9ec', 'grp_92629918b190528ab9ea941cd2e425f2', 'ライトグリーン', '#A7EA9B', 9, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_f764f14f2f985512845f27a266d0f17d', 'grp_92629918b190528ab9ea941cd2e425f2', 'バイオレット', '#AD24EF', 10, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_57b41d6ac5d255f1a18eeb6a854d7548', 'grp_92629918b190528ab9ea941cd2e425f2', 'パールグリーン', '#BEDBC3', 11, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_b37885f24ff15d4f9ae76f412dc7fcd2', 'grp_92629918b190528ab9ea941cd2e425f2', 'パッションピンク', '#EC34F7', 12, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_defa1cf2f1d25339b617b924a03f77b8', 'grp_92629918b190528ab9ea941cd2e425f2', 'オレンジ', '#F19E38', 13, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_8b2d93c75ddc5218b21e0dcabb1b59d7', 'grp_92629918b190528ab9ea941cd2e425f2', 'ブルー', '#0000F1', 14, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_2cb38fd84c285e8aa0b01eecaa58399f', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '白', '#FFFFFF', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_7861e0471b535651960a5f48d333188a', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', 'オレンジ', '#FF8C00', 1, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_a82ebf4d9d2e5091829eb5f7dabad70e', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '青', '#0000FF', 2, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_0e3bcc4b8dc153bfb871430f9b33e9d5', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '黄', '#FFFF00', 3, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_87fc0b6e85de5efa89231f31d6a07a10', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '紫', '#800080', 4, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_ad922d18f82b5cd2a86274118e6d6ca5', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '緑', '#008000', 5, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_713d423be138518ba71ded73fd7acb96', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', 'ピンク', '#FFC0CB', 6, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_7bc01f8b62c552278010d22af934b6fb', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '赤', '#FF0000', 7, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_7aac97d0504756f3979b01d34218416f', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '水色', '#00BFFF', 8, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_8d400b8a4ffc5015ae1fca7b369291b6', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '黄緑', '#7FFF00', 9, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)
VALUES ('col_453d944be3615f218525584a28cbf218', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', 'ターコイズ', '#40E0D0', 10, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');

-- Photo Types / Costumes (Ref: ADR-0021)
INSERT OR IGNORE INTO photo_types (id, group_id, slug, name, display_order, created_at, updated_at)
VALUES ('pht_a3767a13eab9576096db8ebe60c0468c', 'grp_e6722901acc15ce2af3dacee3a83840c', '13th_single', '13th Single 制服', 1, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO photo_types (id, group_id, slug, name, display_order, created_at, updated_at)
VALUES ('pht_7cf4b39551d45e6983f92a8b65d726ee', 'grp_e6722901acc15ce2af3dacee3a83840c', '5th_hinatansai_towel', '5回目のひな誕祭 個別マフラータオル', 2, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO photo_types (id, group_id, slug, name, display_order, created_at, updated_at)
VALUES ('pht_018156cbb46b5dc18b73bbce32f85908', 'grp_e6722901acc15ce2af3dacee3a83840c', '5th_member', '5期生 新メンバー', 3, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO photo_types (id, group_id, slug, name, display_order, created_at, updated_at)
VALUES ('pht_03fa748438005b17821b28150dc4b2f7', 'grp_92629918b190528ab9ea941cd2e425f2', '2nd_album', '2nd Album アー写', 1, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO photo_types (id, group_id, slug, name, display_order, created_at, updated_at)
VALUES ('pht_7313925d7c1f5993ab1ffef4436ede35', 'grp_92629918b190528ab9ea941cd2e425f2', '4th_tour_towel', '4th ARENA TOUR 2024 個別マフラータオル', 2, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO photo_types (id, group_id, slug, name, display_order, created_at, updated_at)
VALUES ('pht_a5fae6c6dc12513d9df6c654d07a51bb', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', 'artist_photo', 'アーティスト写真', 1, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');

-- Idol Members
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_7dfb7abe142b516d914cb16b4b1526c5', 'grp_e6722901acc15ce2af3dacee3a83840c', '上村', 'ひなの', 'かみむら', 'ひなの', 3, 'active', 'col_4f3b1b7030ea5988951210c2472a107c', 'col_67e35b5f6e83555e84caedd87057eb12', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_b8aed4b172365711b1600ea1794c711b', 'grp_e6722901acc15ce2af3dacee3a83840c', '下田', '衣珠季', 'しもだ', 'いずき', 5, 'active', 'col_0f4a27244fdf510f8d7693b6f9392e3d', 'col_4f3b1b7030ea5988951210c2472a107c', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_79623099c3c35bd69b2f88b24d3dad38', 'grp_e6722901acc15ce2af3dacee3a83840c', '丹生', '明里', 'にぶ', 'あかり', 2, 'graduated', 'col_f546c475f62853838cd7527e49a48f5e', 'col_f546c475f62853838cd7527e49a48f5e', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_8fc76fc0b89951cc9fe0b4d28e2dac0c', 'grp_e6722901acc15ce2af3dacee3a83840c', '佐々木', '久美', 'ささき', 'くみ', 1, 'graduated', 'col_0f4a27244fdf510f8d7693b6f9392e3d', 'col_a108b7059664526bb8805f64a3decf7f', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_aefffdf4f6905c66b5a11158cbf4a242', 'grp_e6722901acc15ce2af3dacee3a83840c', '佐々木', '美玲', 'ささき', 'みれい', 1, 'graduated', 'col_7788241b1592544092e9a5e5607ed64f', 'col_7788241b1592544092e9a5e5607ed64f', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_fa28747d4e06546ebac146cf9f946ec5', 'grp_e6722901acc15ce2af3dacee3a83840c', '佐藤', '優羽', 'さとう', 'ゆう', 5, 'active', 'col_4f3b1b7030ea5988951210c2472a107c', 'col_4f3b1b7030ea5988951210c2472a107c', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_194f683faca85e43bcf38b859d845b6c', 'grp_e6722901acc15ce2af3dacee3a83840c', '加藤', '史帆', 'かとう', 'しほ', 1, 'graduated', 'col_b7eaef29bc315b5383a572cd77e9a48f', 'col_b7eaef29bc315b5383a572cd77e9a48f', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_6af22f9136a85bfe98ba4ac3b59fa430', 'grp_e6722901acc15ce2af3dacee3a83840c', '坂井', '新奈', 'さかい', 'にいな', 5, 'active', 'col_1435c4981994548bb842ef227defb786', 'col_1435c4981994548bb842ef227defb786', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_9dc9d92a001e57c58072ae318df0ecdd', 'grp_e6722901acc15ce2af3dacee3a83840c', '大田', '美月', 'おおた', 'みづき', 5, 'active', 'col_300e79231fd95edaab4d85033a1ba80e', 'col_cc3e50e4389256d981cc9584109e5582', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_7fbd1b67056f567795162f8c614a9b8f', 'grp_e6722901acc15ce2af3dacee3a83840c', '大野', '愛実', 'おおの', 'まなみ', 5, 'active', 'col_67e35b5f6e83555e84caedd87057eb12', 'col_67e35b5f6e83555e84caedd87057eb12', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_da56e038da335909bceca8f1ff77a539', 'grp_e6722901acc15ce2af3dacee3a83840c', '宮地', 'すみれ', 'みやち', 'すみれ', 4, 'active', 'col_d94c1d31357d5c799aae0afe2481d356', 'col_67e35b5f6e83555e84caedd87057eb12', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_be84efb349505cdb96ea0f3de6bdea07', 'grp_e6722901acc15ce2af3dacee3a83840c', '富田', '鈴花', 'とみた', 'すずか', 2, 'active', 'col_a108b7059664526bb8805f64a3decf7f', 'col_a108b7059664526bb8805f64a3decf7f', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_3ce56f5368fc51ccbcaff43ba2678e14', 'grp_e6722901acc15ce2af3dacee3a83840c', '小坂', '菜緒', 'こさか', 'なお', 2, 'active', 'col_1435c4981994548bb842ef227defb786', 'col_d94c1d31357d5c799aae0afe2481d356', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_ee9252bc92565c8987249c1705d54b81', 'grp_e6722901acc15ce2af3dacee3a83840c', '小西', '夏菜実', 'こにし', 'ななみ', 4, 'active', 'col_a108b7059664526bb8805f64a3decf7f', 'col_b7eaef29bc315b5383a572cd77e9a48f', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_affb4bacb0d75f3cae144021cc179d3d', 'grp_e6722901acc15ce2af3dacee3a83840c', '山下', '葉留花', 'やました', 'はるか', 4, 'active', 'col_1435c4981994548bb842ef227defb786', 'col_4f3b1b7030ea5988951210c2472a107c', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_f4226763e6c9552a9c387d92c0fdfe30', 'grp_e6722901acc15ce2af3dacee3a83840c', '山口', '陽世', 'やまぐち', 'はるよ', 3, 'active', 'col_3cb2538786e6515e8bd1c6269b53d8e4', 'col_7788241b1592544092e9a5e5607ed64f', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_c72c2fb7bb7d5bd897c9062cb17176fb', 'grp_e6722901acc15ce2af3dacee3a83840c', '平尾', '帆夏', 'ひらお', 'ほのか', 4, 'active', 'col_0f4a27244fdf510f8d7693b6f9392e3d', 'col_f546c475f62853838cd7527e49a48f5e', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_bc4804c468b25fa89cc1e568e76203eb', 'grp_e6722901acc15ce2af3dacee3a83840c', '平岡', '海月', 'ひらおか', 'みつき', 4, 'active', 'col_b7eaef29bc315b5383a572cd77e9a48f', 'col_7788241b1592544092e9a5e5607ed64f', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_e0f4fe5b5493518b891bcce77fe308f3', 'grp_e6722901acc15ce2af3dacee3a83840c', '東村', '芽依', 'ひがしむら', 'めい', 1, 'graduated', 'col_300e79231fd95edaab4d85033a1ba80e', 'col_300e79231fd95edaab4d85033a1ba80e', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_e44f49a59156551cb9f7fcd91d24faa1', 'grp_e6722901acc15ce2af3dacee3a83840c', '松尾', '桜', 'まつお', 'さくら', 5, 'active', 'col_300e79231fd95edaab4d85033a1ba80e', 'col_1435c4981994548bb842ef227defb786', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_002a63d1dd7556b788df1ca67347dffc', 'grp_e6722901acc15ce2af3dacee3a83840c', '松田', '好花', 'まつだ', 'このか', 2, 'active', 'col_3cb2538786e6515e8bd1c6269b53d8e4', 'col_300e79231fd95edaab4d85033a1ba80e', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_5ec3d7cd9b5352b5b485607d96c791f1', 'grp_e6722901acc15ce2af3dacee3a83840c', '森本', '茉莉', 'もりもと', 'まりぃ', 3, 'active', 'col_f546c475f62853838cd7527e49a48f5e', 'col_b7eaef29bc315b5383a572cd77e9a48f', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_93989e0003815378bcef9beab6a6417b', 'grp_e6722901acc15ce2af3dacee3a83840c', '正源司', '陽子', 'しょうげんじ', 'ようこ', 4, 'active', 'col_f546c475f62853838cd7527e49a48f5e', 'col_67e35b5f6e83555e84caedd87057eb12', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_dbedef91333c5dbe958d62c5c9f1e95d', 'grp_e6722901acc15ce2af3dacee3a83840c', '河田', '陽菜', 'かわた', 'ひな', 2, 'active', 'col_7788241b1592544092e9a5e5607ed64f', 'col_300e79231fd95edaab4d85033a1ba80e', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_ed3cee789f825b3d91c043676602d58e', 'grp_e6722901acc15ce2af3dacee3a83840c', '清水', '理央', 'しみず', 'りお', 4, 'active', 'col_0f4a27244fdf510f8d7693b6f9392e3d', 'col_cc3e50e4389256d981cc9584109e5582', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_9719a28cade6554086b6c35810a5997a', 'grp_e6722901acc15ce2af3dacee3a83840c', '渡辺', '莉奈', 'わたなべ', 'りな', 4, 'active', 'col_b7eaef29bc315b5383a572cd77e9a48f', 'col_1435c4981994548bb842ef227defb786', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_42d807c188dc5d65adba6fa5676f5221', 'grp_e6722901acc15ce2af3dacee3a83840c', '濱岸', 'ひより', 'はまぎし', 'ひより', 2, 'graduated', 'col_1435c4981994548bb842ef227defb786', 'col_f546c475f62853838cd7527e49a48f5e', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_a203dc50e87850f9ab52f0edb6aeacdc', 'grp_e6722901acc15ce2af3dacee3a83840c', '片山', '紗希', 'かたやま', 'さき', 5, 'active', 'col_0f4a27244fdf510f8d7693b6f9392e3d', 'col_0f4a27244fdf510f8d7693b6f9392e3d', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_f6d14207570e54ceb95a464dae0d760c', 'grp_e6722901acc15ce2af3dacee3a83840c', '石塚', '瑶季', 'いしづか', 'たまき', 4, 'active', 'col_300e79231fd95edaab4d85033a1ba80e', 'col_f546c475f62853838cd7527e49a48f5e', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_46ba7524619856c58dd99f91ce69b6a5', 'grp_e6722901acc15ce2af3dacee3a83840c', '竹内', '希来里', 'たけうち', 'きらり', 4, 'active', 'col_7788241b1592544092e9a5e5607ed64f', 'col_67e35b5f6e83555e84caedd87057eb12', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_e1feb6f0e02e5cdf932f32333b163411', 'grp_e6722901acc15ce2af3dacee3a83840c', '蔵盛', '妃那乃', 'くらもり', 'ひなの', 5, 'active', 'col_300e79231fd95edaab4d85033a1ba80e', 'col_67e35b5f6e83555e84caedd87057eb12', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_6e656285c7ba56b1accd34800f77eab6', 'grp_e6722901acc15ce2af3dacee3a83840c', '藤嶌', '果歩', 'ふじしま', 'かほ', 4, 'active', 'col_300e79231fd95edaab4d85033a1ba80e', 'col_b7eaef29bc315b5383a572cd77e9a48f', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_9fbea31ccf92550aa5da325c17d09c64', 'grp_e6722901acc15ce2af3dacee3a83840c', '金村', '美玖', 'かねむら', 'みく', 2, 'active', 'col_0f4a27244fdf510f8d7693b6f9392e3d', 'col_7788241b1592544092e9a5e5607ed64f', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_e8a3cef052b15f28a23b5a6eb84dc99d', 'grp_e6722901acc15ce2af3dacee3a83840c', '高井', '俐香', 'たかい', 'りか', 5, 'active', 'col_a108b7059664526bb8805f64a3decf7f', 'col_7788241b1592544092e9a5e5607ed64f', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_2098487fb2b45b129414de6e61808ec3', 'grp_e6722901acc15ce2af3dacee3a83840c', '高本', '彩花', 'たかもと', 'あやか', 1, 'graduated', 'col_1435c4981994548bb842ef227defb786', 'col_4f3b1b7030ea5988951210c2472a107c', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_6c4b735992ef5962bf0b3aff3369675e', 'grp_e6722901acc15ce2af3dacee3a83840c', '高瀬', '愛奈', 'たかせ', 'まな', 1, 'graduated', 'col_1435c4981994548bb842ef227defb786', 'col_cc3e50e4389256d981cc9584109e5582', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_2bfae489f3d855a29a6f892a5ddbe65a', 'grp_e6722901acc15ce2af3dacee3a83840c', '髙橋', '未来虹', 'たかはし', 'みくに', 3, 'active', 'col_c26b71516fc255c092b8219fdca71cff', 'col_a108b7059664526bb8805f64a3decf7f', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_7d4191c0d176566b9af06261ef10e653', 'grp_e6722901acc15ce2af3dacee3a83840c', '鶴崎', '仁香', 'つるさき', 'にこ', 5, 'active', 'col_7788241b1592544092e9a5e5607ed64f', 'col_f546c475f62853838cd7527e49a48f5e', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_557bdbe582b65aaa8bda577d6b8eaf0a', 'grp_e6722901acc15ce2af3dacee3a83840c', '齊藤', '京子', 'さいとう', 'きょうこ', 1, 'graduated', 'col_1435c4981994548bb842ef227defb786', 'col_1435c4981994548bb842ef227defb786', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_7550f1fb98455b3d908d3e1438d08cbb', 'grp_92629918b190528ab9ea941cd2e425f2', '中嶋', '優月', 'なかしま', 'ゆづき', 3, 'active', 'col_1505a540342b58efb1aa96c715a06c2e', 'col_1505a540342b58efb1aa96c715a06c2e', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_d38196cf0669533c9955bb5cbaffa794', 'grp_92629918b190528ab9ea941cd2e425f2', '中川', '智尋', 'なかがわ', 'ちひろ', 4, 'active', 'col_25dddd3002ee511aaa393bece18c807e', 'col_f764f14f2f985512845f27a266d0f17d', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_77120098dfd1559bb76b0ac075274c71', 'grp_92629918b190528ab9ea941cd2e425f2', '井上', '梨名', 'いのうえ', 'りな', 2, 'active', 'col_8b2d93c75ddc5218b21e0dcabb1b59d7', 'col_8b2d93c75ddc5218b21e0dcabb1b59d7', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_8d052fe65505563697db724e25831609', 'grp_92629918b190528ab9ea941cd2e425f2', '佐藤', '愛桜', 'さとう', 'ねお', 4, 'active', 'col_58beea4b0fcf54f39debdb8dc08a788d', 'col_e3452f29e6e1528a94a8d21f2b1bfcce', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_c60767d6b3995b9cbec82db107c45e77', 'grp_92629918b190528ab9ea941cd2e425f2', '勝又', '春', 'かつまた', 'はる', 4, 'active', 'col_58beea4b0fcf54f39debdb8dc08a788d', 'col_ca6ecff6d4c65d1c87571c5c7e13d4c1', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_0123417027f2515792cea1b774422504', 'grp_92629918b190528ab9ea941cd2e425f2', '向井', '純葉', 'むかい', 'いとは', 3, 'active', 'col_e3452f29e6e1528a94a8d21f2b1bfcce', 'col_adfd2542f6125729be52506ccc9ba9a7', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_17f94a6f6a4f55ddb12ef3e937951061', 'grp_92629918b190528ab9ea941cd2e425f2', '増本', '綺良', 'ますもと', 'きら', 2, 'active', 'col_defa1cf2f1d25339b617b924a03f77b8', 'col_defa1cf2f1d25339b617b924a03f77b8', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_fab118ced9865acd981e663ed8ceb7c9', 'grp_92629918b190528ab9ea941cd2e425f2', '大園', '玲', 'おおぞの', 'れい', 2, 'active', 'col_f764f14f2f985512845f27a266d0f17d', 'col_f764f14f2f985512845f27a266d0f17d', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_2d809d417aaf5fed96486a56c24879be', 'grp_92629918b190528ab9ea941cd2e425f2', '大沼', '晶保', 'おおぬま', 'あきほ', 2, 'active', 'col_25dddd3002ee511aaa393bece18c807e', 'col_e3452f29e6e1528a94a8d21f2b1bfcce', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_0691924b45ba537eb8a739a52122a040', 'grp_92629918b190528ab9ea941cd2e425f2', '守屋', '麗奈', 'もりや', 'れな', 2, 'active', 'col_25dddd3002ee511aaa393bece18c807e', 'col_1505a540342b58efb1aa96c715a06c2e', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_30c987b03bf75afab9b676f2f5d7d761', 'grp_92629918b190528ab9ea941cd2e425f2', '小島', '凪紗', 'こじま', 'なぎさ', 3, 'active', 'col_e3452f29e6e1528a94a8d21f2b1bfcce', 'col_defa1cf2f1d25339b617b924a03f77b8', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_1e5f31505fcf562598eb6835d9cb7017', 'grp_92629918b190528ab9ea941cd2e425f2', '小池', '美波', 'こいけ', 'みなみ', 1, 'graduated', 'col_7c98f5489b3253e68a834ff2b2f54bba', 'col_58beea4b0fcf54f39debdb8dc08a788d', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_18f81f86103e530c83029797f5ddef53', 'grp_92629918b190528ab9ea941cd2e425f2', '小田倉', '麗奈', 'おだくら', 'れいな', 3, 'active', 'col_7c98f5489b3253e68a834ff2b2f54bba', 'col_58beea4b0fcf54f39debdb8dc08a788d', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_cbf48a1ef0ba55838b20daec8ac4a584', 'grp_92629918b190528ab9ea941cd2e425f2', '山下', '瞳月', 'やました', 'しづき', 3, 'active', 'col_ca6ecff6d4c65d1c87571c5c7e13d4c1', 'col_e3452f29e6e1528a94a8d21f2b1bfcce', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_27a7aab4d3d75ccda67f8d3a9537be63', 'grp_92629918b190528ab9ea941cd2e425f2', '山川', '宇衣', 'やまかわ', 'うい', 4, 'active', 'col_7c98f5489b3253e68a834ff2b2f54bba', 'col_e3452f29e6e1528a94a8d21f2b1bfcce', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_a5ff8617344859cc83f0283976298c25', 'grp_92629918b190528ab9ea941cd2e425f2', '山田', '桃実', 'やまだ', 'ももみ', 4, 'active', 'col_e3452f29e6e1528a94a8d21f2b1bfcce', 'col_f764f14f2f985512845f27a266d0f17d', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_4682dd06532d525eada319118369d3a1', 'grp_92629918b190528ab9ea941cd2e425f2', '山﨑', '天', 'やまさき', 'てん', 2, 'active', 'col_7c98f5489b3253e68a834ff2b2f54bba', 'col_ef16cc72c68a5f37b0e1de514356d205', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_832e5906aa2350ccac5dfa4d9cf80c6e', 'grp_92629918b190528ab9ea941cd2e425f2', '幸阪', '茉里乃', 'こうさか', 'まりの', 2, 'active', 'col_58beea4b0fcf54f39debdb8dc08a788d', 'col_57b41d6ac5d255f1a18eeb6a854d7548', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_a18f6a3db23358e3bc926a160cde54e9', 'grp_92629918b190528ab9ea941cd2e425f2', '村井', '優', 'むらい', 'ゆう', 3, 'active', 'col_3f3855999d3b5f31817e36ceee850eb9', 'col_8b2d93c75ddc5218b21e0dcabb1b59d7', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_72fcd84ec1545dd4b22c1a3feae5343d', 'grp_92629918b190528ab9ea941cd2e425f2', '村山', '美羽', 'むらやま', 'みう', 3, 'active', 'col_3f3855999d3b5f31817e36ceee850eb9', 'col_8b2d93c75ddc5218b21e0dcabb1b59d7', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_22ece5b62004540eb1070bd9f76817a6', 'grp_92629918b190528ab9ea941cd2e425f2', '松本', '和子', 'まつもと', 'わこ', 4, 'active', 'col_7c98f5489b3253e68a834ff2b2f54bba', 'col_adfd2542f6125729be52506ccc9ba9a7', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_ad244c328d655784b06e124a84502c20', 'grp_92629918b190528ab9ea941cd2e425f2', '松田', '里奈', 'まつだ', 'りな', 2, 'active', 'col_ef16cc72c68a5f37b0e1de514356d205', 'col_25dddd3002ee511aaa393bece18c807e', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_02371e75dd1a54329cf6529e614f323f', 'grp_92629918b190528ab9ea941cd2e425f2', '森田', 'ひかる', 'もりた', 'ひかる', 2, 'active', 'col_ca6ecff6d4c65d1c87571c5c7e13d4c1', 'col_8b2d93c75ddc5218b21e0dcabb1b59d7', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_ef141612bb7050259ad94fbe98990b93', 'grp_92629918b190528ab9ea941cd2e425f2', '武元', '唯衣', 'たけもと', 'ゆい', 2, 'active', 'col_b37885f24ff15d4f9ae76f412dc7fcd2', 'col_8b2d93c75ddc5218b21e0dcabb1b59d7', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_652418691e795202b9f2aff5fae6477b', 'grp_92629918b190528ab9ea941cd2e425f2', '浅井', '恋乃未', 'あさい', 'このみ', 4, 'active', 'col_ca6ecff6d4c65d1c87571c5c7e13d4c1', 'col_adfd2542f6125729be52506ccc9ba9a7', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_9b900e3d9a815ea6a154d92799d08430', 'grp_92629918b190528ab9ea941cd2e425f2', '田村', '保乃', 'たむら', 'ほの', 2, 'active', 'col_e3452f29e6e1528a94a8d21f2b1bfcce', 'col_e3452f29e6e1528a94a8d21f2b1bfcce', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_564ba06a76b3502fbb951399a5c5d24e', 'grp_92629918b190528ab9ea941cd2e425f2', '的野', '美青', 'まとの', 'みお', 3, 'active', 'col_e3452f29e6e1528a94a8d21f2b1bfcce', 'col_8b2d93c75ddc5218b21e0dcabb1b59d7', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_f25d8752867a51e6b29c26170a1ddafd', 'grp_92629918b190528ab9ea941cd2e425f2', '目黒', '陽色', 'めぐろ', 'ひいろ', 4, 'active', 'col_58beea4b0fcf54f39debdb8dc08a788d', 'col_b37885f24ff15d4f9ae76f412dc7fcd2', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_d2a98fc47bd751ffb69f02300e05f9fc', 'grp_92629918b190528ab9ea941cd2e425f2', '石森', '璃花', 'いしもり', 'りか', 3, 'active', 'col_ef16cc72c68a5f37b0e1de514356d205', 'col_1505a540342b58efb1aa96c715a06c2e', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_eb9f507b74235d9ab3e1759a400becbb', 'grp_92629918b190528ab9ea941cd2e425f2', '稲熊', 'ひな', 'いなぐま', 'ひな', 4, 'active', 'col_adfd2542f6125729be52506ccc9ba9a7', 'col_defa1cf2f1d25339b617b924a03f77b8', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_e21c08bd18f45171bb92edaa956ba233', 'grp_92629918b190528ab9ea941cd2e425f2', '藤吉', '夏鈴', 'ふじよし', 'かりん', 2, 'active', 'col_7c98f5489b3253e68a834ff2b2f54bba', 'col_f764f14f2f985512845f27a266d0f17d', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_eecdf2042be9513bb8de51c027a463a3', 'grp_92629918b190528ab9ea941cd2e425f2', '谷口', '愛季', 'たにぐち', 'あいり', 3, 'active', 'col_ca6ecff6d4c65d1c87571c5c7e13d4c1', 'col_f764f14f2f985512845f27a266d0f17d', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_4de21332af30544e87c1d89bc21d01e1', 'grp_92629918b190528ab9ea941cd2e425f2', '遠藤', '光莉', 'えんどう', 'ひかり', 2, 'active', 'col_3f3855999d3b5f31817e36ceee850eb9', 'col_3f3855999d3b5f31817e36ceee850eb9', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_61023eeb30125bfdb2c2284d3c77b3d6', 'grp_92629918b190528ab9ea941cd2e425f2', '遠藤', '理子', 'えんどう', 'りこ', 3, 'active', 'col_58beea4b0fcf54f39debdb8dc08a788d', 'col_f764f14f2f985512845f27a266d0f17d', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_5bb8d5630c4956c1ba2a63ea8761b9e6', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '伊藤', '理々杏', 'いとう', 'りりあ', 3, 'active', 'col_87fc0b6e85de5efa89231f31d6a07a10', 'col_7bc01f8b62c552278010d22af934b6fb', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_bc7a957b5b0d531da9480fd8943506a6', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '岩本', '蓮加', 'いわもと', 'れんか', 3, 'active', 'col_713d423be138518ba71ded73fd7acb96', 'col_7bc01f8b62c552278010d22af934b6fb', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_916df6220b6755fbb8d4d5736a453d8a', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '梅澤', '美波', 'うめざわ', 'みなみ', 3, 'active', 'col_a82ebf4d9d2e5091829eb5f7dabad70e', 'col_7aac97d0504756f3979b01d34218416f', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_fbdc833f0cb4562c8a60767ce7c6039d', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '久保', '史緒里', 'くぼ', 'しおり', 3, 'active', 'col_7aac97d0504756f3979b01d34218416f', 'col_0e3bcc4b8dc153bfb871430f9b33e9d5', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_b55f84aa951e538b92cf6fab897f1996', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '佐藤', '楓', 'さとう', 'かえで', 3, 'active', 'col_7bc01f8b62c552278010d22af934b6fb', 'col_7bc01f8b62c552278010d22af934b6fb', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_ba886957a68656009e0883affce7df96', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '中村', '麗乃', 'なかむら', 'れの', 3, 'active', 'col_a82ebf4d9d2e5091829eb5f7dabad70e', 'col_2cb38fd84c285e8aa0b01eecaa58399f', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_d45a34bbf5ad585d8e4ef46a589d2c00', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '吉田', '綾乃クリスティー', 'よしだ', 'あやのくりすてぃー', 3, 'active', 'col_713d423be138518ba71ded73fd7acb96', 'col_87fc0b6e85de5efa89231f31d6a07a10', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_5ba3a312bdc55b2aa91175a94878e760', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '与田', '祐希', 'よだ', 'ゆうき', 3, 'active', 'col_7bc01f8b62c552278010d22af934b6fb', 'col_ad922d18f82b5cd2a86274118e6d6ca5', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_c602aee07c595f669c537f7140abc1fa', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '遠藤', 'さくら', 'えんどう', 'さくら', 4, 'active', 'col_2cb38fd84c285e8aa0b01eecaa58399f', 'col_713d423be138518ba71ded73fd7acb96', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_88a6fd58df4057379d255e88d3ad0ba0', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '賀喜', '遥香', 'かき', 'はるか', 4, 'active', 'col_7861e0471b535651960a5f48d333188a', 'col_ad922d18f82b5cd2a86274118e6d6ca5', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_1454226e525550b6996fcceb589e4ffc', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '金川', '紗耶', 'かながわ', 'さや', 4, 'active', 'col_7bc01f8b62c552278010d22af934b6fb', 'col_7aac97d0504756f3979b01d34218416f', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_fedbe59b2ebb540d90a643520479c407', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '黒見', '明香', 'くろみ', 'はるか', 4, 'active', 'col_87fc0b6e85de5efa89231f31d6a07a10', 'col_ad922d18f82b5cd2a86274118e6d6ca5', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_9f6cb5cac6135987b73167203ee8235c', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '佐藤', '璃果', 'さとう', 'りか', 4, 'active', 'col_713d423be138518ba71ded73fd7acb96', 'col_453d944be3615f218525584a28cbf218', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_3fb604b7c78253e58e667751e125b79e', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '柴田', '柚菜', 'しばた', 'ゆな', 4, 'active', 'col_a82ebf4d9d2e5091829eb5f7dabad70e', 'col_8d400b8a4ffc5015ae1fca7b369291b6', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_2d1a0b5c9b4a5402a2cb8737152711e6', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '田村', '真佑', 'たむら', 'まゆ', 4, 'active', 'col_87fc0b6e85de5efa89231f31d6a07a10', 'col_7aac97d0504756f3979b01d34218416f', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_1c731613b2cb5339813a718c55fa3ef8', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '筒井', 'あやめ', 'つつい', 'あやめ', 4, 'active', 'col_87fc0b6e85de5efa89231f31d6a07a10', 'col_87fc0b6e85de5efa89231f31d6a07a10', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_900332b6a7f35d2fb0f779f4025f158f', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '林', '瑠奈', 'はやし', 'るな', 4, 'active', 'col_713d423be138518ba71ded73fd7acb96', 'col_713d423be138518ba71ded73fd7acb96', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_b44ec03b6e0d51d6a43de351bd9629f9', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '松尾', '美佑', 'まつお', 'みゆ', 4, 'active', 'col_453d944be3615f218525584a28cbf218', 'col_2cb38fd84c285e8aa0b01eecaa58399f', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_a3e621228cff565c90b19ee7f36fc06b', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '矢久保', '美緒', 'やくぼ', 'みお', 4, 'active', 'col_0e3bcc4b8dc153bfb871430f9b33e9d5', 'col_713d423be138518ba71ded73fd7acb96', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_4ee76929b757597ba0a78a582d04270a', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '弓木', '奈於', 'ゆみき', 'なお', 4, 'active', 'col_7bc01f8b62c552278010d22af934b6fb', 'col_8d400b8a4ffc5015ae1fca7b369291b6', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_6515da2348d85a4ba0fd6d6000ad8188', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '五百城', '茉央', 'いおき', 'まお', 5, 'active', 'col_453d944be3615f218525584a28cbf218', 'col_a82ebf4d9d2e5091829eb5f7dabad70e', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_36fc8a7f13d05fe88ae58017b3b59d1c', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '池田', '瑛紗', 'いけだ', 'てれさ', 5, 'active', 'col_2cb38fd84c285e8aa0b01eecaa58399f', 'col_ad922d18f82b5cd2a86274118e6d6ca5', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_972e96e488ad5c69a5ca94181967a0f8', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '一ノ瀬', '美空', 'いちのせ', 'みく', 5, 'active', 'col_7aac97d0504756f3979b01d34218416f', 'col_7aac97d0504756f3979b01d34218416f', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_af5652d5e4bf5a06908862e18d47f9d8', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '井上', '和', 'いのうえ', 'なぎ', 5, 'active', 'col_2cb38fd84c285e8aa0b01eecaa58399f', 'col_7bc01f8b62c552278010d22af934b6fb', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_170a8cd7930c512d99c1187064c6ebd4', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '岡本', '姫奈', 'おかもと', 'ひな', 5, 'active', 'col_87fc0b6e85de5efa89231f31d6a07a10', 'col_a82ebf4d9d2e5091829eb5f7dabad70e', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_df93a6771b075440b452957007b2689e', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '小川', '彩', 'おがわ', 'あや', 5, 'active', 'col_2cb38fd84c285e8aa0b01eecaa58399f', 'col_2cb38fd84c285e8aa0b01eecaa58399f', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_076f4ee6f7b05730b15ff56cbd457be7', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '奥田', 'いろは', 'おくだ', 'いろは', 5, 'active', 'col_713d423be138518ba71ded73fd7acb96', 'col_8d400b8a4ffc5015ae1fca7b369291b6', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_e7e29d6c19875964ba0079913195d513', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '川﨑', '桜', 'かわさき', 'さくら', 5, 'active', 'col_713d423be138518ba71ded73fd7acb96', 'col_ad922d18f82b5cd2a86274118e6d6ca5', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_f45a1e45200256bb870fc195e360119a', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '菅原', '咲月', 'すがわら', 'さつき', 5, 'active', 'col_713d423be138518ba71ded73fd7acb96', 'col_7aac97d0504756f3979b01d34218416f', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_c0bafbff935b5eed8ed3e700cbbc09c7', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '冨里', '奈央', 'とみさと', 'なお', 5, 'active', 'col_453d944be3615f218525584a28cbf218', 'col_453d944be3615f218525584a28cbf218', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)
VALUES ('mem_61f64dc955b55de8b3540cc265dd27de', 'grp_fb2466e223f1558ea71bf2d0ba4c7469', '中西', 'アルノ', 'なかにし', 'あるの', 5, 'active', 'col_453d944be3615f218525584a28cbf218', 'col_7aac97d0504756f3979b01d34218416f', 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');

-- Member Images (1:N, Ref: ADR-0021)
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_455e72f40ae75d5281943b482e2d2a95', 'mem_7dfb7abe142b516d914cb16b4b1526c5', 'pht_a3767a13eab9576096db8ebe60c0468c', 'img_455e72f40ae75d5281943b482e2d2a95.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_847a20ba1ae45b5390e2696db99c6dc4', 'mem_b8aed4b172365711b1600ea1794c711b', 'pht_018156cbb46b5dc18b73bbce32f85908', 'img_847a20ba1ae45b5390e2696db99c6dc4.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_d42e599b224c5b34be0b263dd7d9a31f', 'mem_79623099c3c35bd69b2f88b24d3dad38', 'pht_a3767a13eab9576096db8ebe60c0468c', 'img_d42e599b224c5b34be0b263dd7d9a31f.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_e47daec5db0751699f8281ae61064f91', 'mem_8fc76fc0b89951cc9fe0b4d28e2dac0c', 'pht_a3767a13eab9576096db8ebe60c0468c', 'img_e47daec5db0751699f8281ae61064f91.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_6a9df76f45085e43bc913335920a2a75', 'mem_aefffdf4f6905c66b5a11158cbf4a242', 'pht_a3767a13eab9576096db8ebe60c0468c', 'img_6a9df76f45085e43bc913335920a2a75.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_e6486950dcb352f9997964c948c63ecc', 'mem_fa28747d4e06546ebac146cf9f946ec5', 'pht_018156cbb46b5dc18b73bbce32f85908', 'img_e6486950dcb352f9997964c948c63ecc.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_4b57e50edbe6532b9272c5faa7d06dec', 'mem_194f683faca85e43bcf38b859d845b6c', 'pht_7cf4b39551d45e6983f92a8b65d726ee', 'img_4b57e50edbe6532b9272c5faa7d06dec.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_ad3d8ead8ff552ca9a97d379ae5610c7', 'mem_6af22f9136a85bfe98ba4ac3b59fa430', 'pht_018156cbb46b5dc18b73bbce32f85908', 'img_ad3d8ead8ff552ca9a97d379ae5610c7.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_7cd23f4f8e5653ff8b06405ab37626cf', 'mem_9dc9d92a001e57c58072ae318df0ecdd', 'pht_018156cbb46b5dc18b73bbce32f85908', 'img_7cd23f4f8e5653ff8b06405ab37626cf.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_46ad61b687505743b682fb11ed85b576', 'mem_7fbd1b67056f567795162f8c614a9b8f', 'pht_018156cbb46b5dc18b73bbce32f85908', 'img_46ad61b687505743b682fb11ed85b576.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_e1f74b2f2dd956ed9f48e66baf3daaf3', 'mem_da56e038da335909bceca8f1ff77a539', 'pht_a3767a13eab9576096db8ebe60c0468c', 'img_e1f74b2f2dd956ed9f48e66baf3daaf3.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_128124ef289051d8ac0d1c431d7e8b76', 'mem_be84efb349505cdb96ea0f3de6bdea07', 'pht_a3767a13eab9576096db8ebe60c0468c', 'img_128124ef289051d8ac0d1c431d7e8b76.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_11e5867149a653f08e2ea1deb2eea0b0', 'mem_3ce56f5368fc51ccbcaff43ba2678e14', 'pht_a3767a13eab9576096db8ebe60c0468c', 'img_11e5867149a653f08e2ea1deb2eea0b0.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_eea5304d2ad35697a3e2e39934217659', 'mem_ee9252bc92565c8987249c1705d54b81', 'pht_a3767a13eab9576096db8ebe60c0468c', 'img_eea5304d2ad35697a3e2e39934217659.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_db042695dedf575ea063fbd48741313c', 'mem_affb4bacb0d75f3cae144021cc179d3d', 'pht_a3767a13eab9576096db8ebe60c0468c', 'img_db042695dedf575ea063fbd48741313c.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_37980d46169659d3ae82240a2ffc66ea', 'mem_f4226763e6c9552a9c387d92c0fdfe30', 'pht_a3767a13eab9576096db8ebe60c0468c', 'img_37980d46169659d3ae82240a2ffc66ea.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_1398ae5d5a0b5e2eb1083da28f26b261', 'mem_c72c2fb7bb7d5bd897c9062cb17176fb', 'pht_a3767a13eab9576096db8ebe60c0468c', 'img_1398ae5d5a0b5e2eb1083da28f26b261.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_09e30eaf7303566a8a5bf2eeefddf048', 'mem_bc4804c468b25fa89cc1e568e76203eb', 'pht_a3767a13eab9576096db8ebe60c0468c', 'img_09e30eaf7303566a8a5bf2eeefddf048.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_fc8eb2503f4c52b280195c77c1573d5e', 'mem_e0f4fe5b5493518b891bcce77fe308f3', 'pht_7cf4b39551d45e6983f92a8b65d726ee', 'img_fc8eb2503f4c52b280195c77c1573d5e.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_fee5f99c18ea530c80677ccee22880e9', 'mem_e44f49a59156551cb9f7fcd91d24faa1', 'pht_018156cbb46b5dc18b73bbce32f85908', 'img_fee5f99c18ea530c80677ccee22880e9.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_5e8b4187ced354978b711d8145fd8110', 'mem_002a63d1dd7556b788df1ca67347dffc', 'pht_a3767a13eab9576096db8ebe60c0468c', 'img_5e8b4187ced354978b711d8145fd8110.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_df0b3d407f9551609493c198bad21f7a', 'mem_5ec3d7cd9b5352b5b485607d96c791f1', 'pht_a3767a13eab9576096db8ebe60c0468c', 'img_df0b3d407f9551609493c198bad21f7a.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_9cd38926169f54a1a2d69ee7e9ad818c', 'mem_93989e0003815378bcef9beab6a6417b', 'pht_a3767a13eab9576096db8ebe60c0468c', 'img_9cd38926169f54a1a2d69ee7e9ad818c.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_4de5514473695e94aac8c781f3ef5b43', 'mem_dbedef91333c5dbe958d62c5c9f1e95d', 'pht_a3767a13eab9576096db8ebe60c0468c', 'img_4de5514473695e94aac8c781f3ef5b43.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_b2dae00b19145f469ba1d377dc99fa6d', 'mem_ed3cee789f825b3d91c043676602d58e', 'pht_a3767a13eab9576096db8ebe60c0468c', 'img_b2dae00b19145f469ba1d377dc99fa6d.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_6659f3c82b235fd79bdaf33a2451a858', 'mem_9719a28cade6554086b6c35810a5997a', 'pht_a3767a13eab9576096db8ebe60c0468c', 'img_6659f3c82b235fd79bdaf33a2451a858.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_6cbdbfc72f5d557d9f7075b99ce5e26e', 'mem_42d807c188dc5d65adba6fa5676f5221', 'pht_7cf4b39551d45e6983f92a8b65d726ee', 'img_6cbdbfc72f5d557d9f7075b99ce5e26e.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_2e04c092d6ed56cabd8768c2dedd2665', 'mem_a203dc50e87850f9ab52f0edb6aeacdc', 'pht_018156cbb46b5dc18b73bbce32f85908', 'img_2e04c092d6ed56cabd8768c2dedd2665.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_fad119dad25a51e7acfcdf1a743fe338', 'mem_f6d14207570e54ceb95a464dae0d760c', 'pht_a3767a13eab9576096db8ebe60c0468c', 'img_fad119dad25a51e7acfcdf1a743fe338.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_007aea2773945aa0b3f616a3a04c869d', 'mem_46ba7524619856c58dd99f91ce69b6a5', 'pht_a3767a13eab9576096db8ebe60c0468c', 'img_007aea2773945aa0b3f616a3a04c869d.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_8c601e09dba25407bd557a20e5c7a956', 'mem_e1feb6f0e02e5cdf932f32333b163411', 'pht_018156cbb46b5dc18b73bbce32f85908', 'img_8c601e09dba25407bd557a20e5c7a956.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_318d12668c8f5a4eac18c408da34c8a3', 'mem_6e656285c7ba56b1accd34800f77eab6', 'pht_a3767a13eab9576096db8ebe60c0468c', 'img_318d12668c8f5a4eac18c408da34c8a3.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_07aee6bc12f9580dab5a12418264df3f', 'mem_9fbea31ccf92550aa5da325c17d09c64', 'pht_a3767a13eab9576096db8ebe60c0468c', 'img_07aee6bc12f9580dab5a12418264df3f.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_564a605068585d72bcdb3608d7e7a1e2', 'mem_e8a3cef052b15f28a23b5a6eb84dc99d', 'pht_018156cbb46b5dc18b73bbce32f85908', 'img_564a605068585d72bcdb3608d7e7a1e2.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_a8e9f6db42915d1a8a7026afde47793a', 'mem_2098487fb2b45b129414de6e61808ec3', 'pht_7cf4b39551d45e6983f92a8b65d726ee', 'img_a8e9f6db42915d1a8a7026afde47793a.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_590214468c4c5cf198afeb3d453b50e6', 'mem_6c4b735992ef5962bf0b3aff3369675e', 'pht_a3767a13eab9576096db8ebe60c0468c', 'img_590214468c4c5cf198afeb3d453b50e6.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_57b9bb4ae04a5a9d89fdc119b2620e31', 'mem_2bfae489f3d855a29a6f892a5ddbe65a', 'pht_a3767a13eab9576096db8ebe60c0468c', 'img_57b9bb4ae04a5a9d89fdc119b2620e31.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_eb3e8032a1e55308b9f8f8e3bdc8a336', 'mem_7d4191c0d176566b9af06261ef10e653', 'pht_018156cbb46b5dc18b73bbce32f85908', 'img_eb3e8032a1e55308b9f8f8e3bdc8a336.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_70d464ba4e765cf5880c7b98c4cdb7fc', 'mem_557bdbe582b65aaa8bda577d6b8eaf0a', 'pht_7cf4b39551d45e6983f92a8b65d726ee', 'img_70d464ba4e765cf5880c7b98c4cdb7fc.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_79fb832d845a571ea74eb1e93ae73f29', 'mem_7550f1fb98455b3d908d3e1438d08cbb', 'pht_03fa748438005b17821b28150dc4b2f7', 'img_79fb832d845a571ea74eb1e93ae73f29.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_9a738c9f4bed5c119697df6ecada2118', 'mem_d38196cf0669533c9955bb5cbaffa794', 'pht_03fa748438005b17821b28150dc4b2f7', 'img_9a738c9f4bed5c119697df6ecada2118.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_51053d00961e5c608db9c50e77f17b9a', 'mem_77120098dfd1559bb76b0ac075274c71', 'pht_03fa748438005b17821b28150dc4b2f7', 'img_51053d00961e5c608db9c50e77f17b9a.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_2244b2278fb558118c3474f622999e1e', 'mem_8d052fe65505563697db724e25831609', 'pht_03fa748438005b17821b28150dc4b2f7', 'img_2244b2278fb558118c3474f622999e1e.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_1343d055447c54818b4ca63acd624b05', 'mem_c60767d6b3995b9cbec82db107c45e77', 'pht_03fa748438005b17821b28150dc4b2f7', 'img_1343d055447c54818b4ca63acd624b05.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_8e752b142e0f5dabb33f8dcba9d4000c', 'mem_0123417027f2515792cea1b774422504', 'pht_03fa748438005b17821b28150dc4b2f7', 'img_8e752b142e0f5dabb33f8dcba9d4000c.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_2bf30fee745d5c53823ff16a97b39fb3', 'mem_17f94a6f6a4f55ddb12ef3e937951061', 'pht_03fa748438005b17821b28150dc4b2f7', 'img_2bf30fee745d5c53823ff16a97b39fb3.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_a7095c3e5a9654899ab7ca3ee726032e', 'mem_fab118ced9865acd981e663ed8ceb7c9', 'pht_03fa748438005b17821b28150dc4b2f7', 'img_a7095c3e5a9654899ab7ca3ee726032e.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_7a5d9c12b3375361b2bf6497cf0840e0', 'mem_2d809d417aaf5fed96486a56c24879be', 'pht_03fa748438005b17821b28150dc4b2f7', 'img_7a5d9c12b3375361b2bf6497cf0840e0.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_53833025202854d29f5bff297b91d617', 'mem_0691924b45ba537eb8a739a52122a040', 'pht_03fa748438005b17821b28150dc4b2f7', 'img_53833025202854d29f5bff297b91d617.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_211a6c71e9af536298e1dc894c23ebe5', 'mem_30c987b03bf75afab9b676f2f5d7d761', 'pht_03fa748438005b17821b28150dc4b2f7', 'img_211a6c71e9af536298e1dc894c23ebe5.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_1e99e94bd1295be68fc713b800a42919', 'mem_1e5f31505fcf562598eb6835d9cb7017', 'pht_03fa748438005b17821b28150dc4b2f7', 'img_1e99e94bd1295be68fc713b800a42919.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_4be90f0be129579daf8e9d987af14a03', 'mem_18f81f86103e530c83029797f5ddef53', 'pht_03fa748438005b17821b28150dc4b2f7', 'img_4be90f0be129579daf8e9d987af14a03.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_d31accff20855c53ae58176a6d4d6f7a', 'mem_cbf48a1ef0ba55838b20daec8ac4a584', 'pht_03fa748438005b17821b28150dc4b2f7', 'img_d31accff20855c53ae58176a6d4d6f7a.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_abdf2137ef83576cbda9885ac76f2110', 'mem_27a7aab4d3d75ccda67f8d3a9537be63', 'pht_03fa748438005b17821b28150dc4b2f7', 'img_abdf2137ef83576cbda9885ac76f2110.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_92580a8a37285fb58a55c47e7e6d835c', 'mem_a5ff8617344859cc83f0283976298c25', 'pht_03fa748438005b17821b28150dc4b2f7', 'img_92580a8a37285fb58a55c47e7e6d835c.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_13b028aafe2057ed8fa99707b5e2cf3a', 'mem_4682dd06532d525eada319118369d3a1', 'pht_03fa748438005b17821b28150dc4b2f7', 'img_13b028aafe2057ed8fa99707b5e2cf3a.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_23ee82ba2b7756a483e679055505b335', 'mem_832e5906aa2350ccac5dfa4d9cf80c6e', 'pht_03fa748438005b17821b28150dc4b2f7', 'img_23ee82ba2b7756a483e679055505b335.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_c5afacf251385b9da5c170d8d10a6cd2', 'mem_a18f6a3db23358e3bc926a160cde54e9', 'pht_03fa748438005b17821b28150dc4b2f7', 'img_c5afacf251385b9da5c170d8d10a6cd2.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_805998d4052759cf924daee7a09ff042', 'mem_72fcd84ec1545dd4b22c1a3feae5343d', 'pht_03fa748438005b17821b28150dc4b2f7', 'img_805998d4052759cf924daee7a09ff042.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_d939f11dfd9c5aac81b939441ceb9587', 'mem_22ece5b62004540eb1070bd9f76817a6', 'pht_03fa748438005b17821b28150dc4b2f7', 'img_d939f11dfd9c5aac81b939441ceb9587.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_1a98968441d0518bb125a872da53848f', 'mem_ad244c328d655784b06e124a84502c20', 'pht_03fa748438005b17821b28150dc4b2f7', 'img_1a98968441d0518bb125a872da53848f.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_a0a7a8df5fd755f8a25c2c8042d1e299', 'mem_02371e75dd1a54329cf6529e614f323f', 'pht_03fa748438005b17821b28150dc4b2f7', 'img_a0a7a8df5fd755f8a25c2c8042d1e299.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_5f26a2dd6976518eaca08f4187540c69', 'mem_ef141612bb7050259ad94fbe98990b93', 'pht_03fa748438005b17821b28150dc4b2f7', 'img_5f26a2dd6976518eaca08f4187540c69.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_9bec0c8b4c165bee82f9c33787730425', 'mem_652418691e795202b9f2aff5fae6477b', 'pht_03fa748438005b17821b28150dc4b2f7', 'img_9bec0c8b4c165bee82f9c33787730425.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_7639803534265aad90c1e00b00eee2cb', 'mem_9b900e3d9a815ea6a154d92799d08430', 'pht_03fa748438005b17821b28150dc4b2f7', 'img_7639803534265aad90c1e00b00eee2cb.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_c375e30dc3e457bea1993b4bafdccc24', 'mem_564ba06a76b3502fbb951399a5c5d24e', 'pht_03fa748438005b17821b28150dc4b2f7', 'img_c375e30dc3e457bea1993b4bafdccc24.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_f42676ee14765390b1522e7e0683a054', 'mem_f25d8752867a51e6b29c26170a1ddafd', 'pht_03fa748438005b17821b28150dc4b2f7', 'img_f42676ee14765390b1522e7e0683a054.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_48a9dd7e66475e8681726fdeaef3c348', 'mem_d2a98fc47bd751ffb69f02300e05f9fc', 'pht_03fa748438005b17821b28150dc4b2f7', 'img_48a9dd7e66475e8681726fdeaef3c348.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_9f405a8b75f15f7dadeb00cbf5f996b5', 'mem_eb9f507b74235d9ab3e1759a400becbb', 'pht_03fa748438005b17821b28150dc4b2f7', 'img_9f405a8b75f15f7dadeb00cbf5f996b5.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_2c49eb8c0d62509380fdf68375903ce1', 'mem_e21c08bd18f45171bb92edaa956ba233', 'pht_03fa748438005b17821b28150dc4b2f7', 'img_2c49eb8c0d62509380fdf68375903ce1.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_fc60c6b7ed515bfcaae3496b6050667a', 'mem_eecdf2042be9513bb8de51c027a463a3', 'pht_03fa748438005b17821b28150dc4b2f7', 'img_fc60c6b7ed515bfcaae3496b6050667a.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_bfd0bb5f370e5c20a0b8c0cae0ef44e3', 'mem_4de21332af30544e87c1d89bc21d01e1', 'pht_03fa748438005b17821b28150dc4b2f7', 'img_bfd0bb5f370e5c20a0b8c0cae0ef44e3.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_7acf8543cede556581254eea3a473f47', 'mem_61023eeb30125bfdb2c2284d3c77b3d6', 'pht_03fa748438005b17821b28150dc4b2f7', 'img_7acf8543cede556581254eea3a473f47.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_633021fe5ee959ac841ec699dbfdf709', 'mem_5bb8d5630c4956c1ba2a63ea8761b9e6', 'pht_a5fae6c6dc12513d9df6c654d07a51bb', 'img_633021fe5ee959ac841ec699dbfdf709.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_8b1125f1df685d98975b2e6ebe4fbe8e', 'mem_bc7a957b5b0d531da9480fd8943506a6', 'pht_a5fae6c6dc12513d9df6c654d07a51bb', 'img_8b1125f1df685d98975b2e6ebe4fbe8e.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_81795641ee3155668bb1e9ed0ce108a2', 'mem_916df6220b6755fbb8d4d5736a453d8a', 'pht_a5fae6c6dc12513d9df6c654d07a51bb', 'img_81795641ee3155668bb1e9ed0ce108a2.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_0e28988dbed455388898034be781219f', 'mem_fbdc833f0cb4562c8a60767ce7c6039d', 'pht_a5fae6c6dc12513d9df6c654d07a51bb', 'img_0e28988dbed455388898034be781219f.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_3f2088f3819352b7b9902a3c636bcc62', 'mem_b55f84aa951e538b92cf6fab897f1996', 'pht_a5fae6c6dc12513d9df6c654d07a51bb', 'img_3f2088f3819352b7b9902a3c636bcc62.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_f97484a80af3581cae8298a07323f39e', 'mem_ba886957a68656009e0883affce7df96', 'pht_a5fae6c6dc12513d9df6c654d07a51bb', 'img_f97484a80af3581cae8298a07323f39e.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_d32aedd04bc55ba989d83c78dd708e93', 'mem_d45a34bbf5ad585d8e4ef46a589d2c00', 'pht_a5fae6c6dc12513d9df6c654d07a51bb', 'img_d32aedd04bc55ba989d83c78dd708e93.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_864348581c795295b48fbda617a3750b', 'mem_5ba3a312bdc55b2aa91175a94878e760', 'pht_a5fae6c6dc12513d9df6c654d07a51bb', 'img_864348581c795295b48fbda617a3750b.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_90f99d1977865cf3b49f6e42c3933700', 'mem_c602aee07c595f669c537f7140abc1fa', 'pht_a5fae6c6dc12513d9df6c654d07a51bb', 'img_90f99d1977865cf3b49f6e42c3933700.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_26f9a0f3ab8256caa73f24bd7625a24b', 'mem_88a6fd58df4057379d255e88d3ad0ba0', 'pht_a5fae6c6dc12513d9df6c654d07a51bb', 'img_26f9a0f3ab8256caa73f24bd7625a24b.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_b9bdbc19b18a565da8eebf00307b3cc1', 'mem_1454226e525550b6996fcceb589e4ffc', 'pht_a5fae6c6dc12513d9df6c654d07a51bb', 'img_b9bdbc19b18a565da8eebf00307b3cc1.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_0cb65c9a8b9e5aa3bd9e78693aa30592', 'mem_fedbe59b2ebb540d90a643520479c407', 'pht_a5fae6c6dc12513d9df6c654d07a51bb', 'img_0cb65c9a8b9e5aa3bd9e78693aa30592.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_f930801f7f535614a30ee4e5fc31aa02', 'mem_9f6cb5cac6135987b73167203ee8235c', 'pht_a5fae6c6dc12513d9df6c654d07a51bb', 'img_f930801f7f535614a30ee4e5fc31aa02.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_5a18d56479085112a8c3743880f3c8be', 'mem_3fb604b7c78253e58e667751e125b79e', 'pht_a5fae6c6dc12513d9df6c654d07a51bb', 'img_5a18d56479085112a8c3743880f3c8be.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_68f0997c80455eb5add619a60822031e', 'mem_2d1a0b5c9b4a5402a2cb8737152711e6', 'pht_a5fae6c6dc12513d9df6c654d07a51bb', 'img_68f0997c80455eb5add619a60822031e.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_53cf2e59c5d3515e832fb760e522acb7', 'mem_1c731613b2cb5339813a718c55fa3ef8', 'pht_a5fae6c6dc12513d9df6c654d07a51bb', 'img_53cf2e59c5d3515e832fb760e522acb7.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_19d2ff5124995238993ce849e493f1a0', 'mem_900332b6a7f35d2fb0f779f4025f158f', 'pht_a5fae6c6dc12513d9df6c654d07a51bb', 'img_19d2ff5124995238993ce849e493f1a0.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_922749481c4655d18207361cfb6305d2', 'mem_b44ec03b6e0d51d6a43de351bd9629f9', 'pht_a5fae6c6dc12513d9df6c654d07a51bb', 'img_922749481c4655d18207361cfb6305d2.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_1b95df4565f35ddea43de8f0db99e80f', 'mem_a3e621228cff565c90b19ee7f36fc06b', 'pht_a5fae6c6dc12513d9df6c654d07a51bb', 'img_1b95df4565f35ddea43de8f0db99e80f.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_0ba446fcdcfb5979bb25afa75fb426d7', 'mem_4ee76929b757597ba0a78a582d04270a', 'pht_a5fae6c6dc12513d9df6c654d07a51bb', 'img_0ba446fcdcfb5979bb25afa75fb426d7.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_85b179c7c0b55e70931593bf1227a871', 'mem_6515da2348d85a4ba0fd6d6000ad8188', 'pht_a5fae6c6dc12513d9df6c654d07a51bb', 'img_85b179c7c0b55e70931593bf1227a871.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_ee2485aab58251c5af26412e3df32647', 'mem_36fc8a7f13d05fe88ae58017b3b59d1c', 'pht_a5fae6c6dc12513d9df6c654d07a51bb', 'img_ee2485aab58251c5af26412e3df32647.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_ccdf1f3933e55d1dba27cf20b6d2797a', 'mem_972e96e488ad5c69a5ca94181967a0f8', 'pht_a5fae6c6dc12513d9df6c654d07a51bb', 'img_ccdf1f3933e55d1dba27cf20b6d2797a.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_92eb0d03e92f50aa996c647124863bc7', 'mem_af5652d5e4bf5a06908862e18d47f9d8', 'pht_a5fae6c6dc12513d9df6c654d07a51bb', 'img_92eb0d03e92f50aa996c647124863bc7.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_a5b5b097cf1c5e53a683ce6188657d6a', 'mem_170a8cd7930c512d99c1187064c6ebd4', 'pht_a5fae6c6dc12513d9df6c654d07a51bb', 'img_a5b5b097cf1c5e53a683ce6188657d6a.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_336de6274f3855d0ac1ebe93e616ce43', 'mem_df93a6771b075440b452957007b2689e', 'pht_a5fae6c6dc12513d9df6c654d07a51bb', 'img_336de6274f3855d0ac1ebe93e616ce43.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_1e2b9eb5976a5016a05a4e75cebf3ba7', 'mem_076f4ee6f7b05730b15ff56cbd457be7', 'pht_a5fae6c6dc12513d9df6c654d07a51bb', 'img_1e2b9eb5976a5016a05a4e75cebf3ba7.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_2648ee7d6b585251a2fb718857021c5f', 'mem_e7e29d6c19875964ba0079913195d513', 'pht_a5fae6c6dc12513d9df6c654d07a51bb', 'img_2648ee7d6b585251a2fb718857021c5f.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_5396336c1a29549087224b695b975254', 'mem_f45a1e45200256bb870fc195e360119a', 'pht_a5fae6c6dc12513d9df6c654d07a51bb', 'img_5396336c1a29549087224b695b975254.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_039f3b449f32571f9de521899a193933', 'mem_c0bafbff935b5eed8ed3e700cbbc09c7', 'pht_a5fae6c6dc12513d9df6c654d07a51bb', 'img_039f3b449f32571f9de521899a193933.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');
INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)
VALUES ('img_b84c0981292159e3afcac4e68a61c586', 'mem_61f64dc955b55de8b3540cc265dd27de', 'pht_a5fae6c6dc12513d9df6c654d07a51bb', 'img_b84c0981292159e3afcac4e68a61c586.webp', 1, 0, '2026-10-04T00:00:00Z', '2026-10-04T00:00:00Z');

-- Master Version (Ref: ADR-0021)
INSERT OR REPLACE INTO master_versions (id, version, updated_at)
VALUES ('current', '2026.10.04-1', '2026-10-04T00:00:00Z');
