//go:build ignore

package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/google/uuid"
)

// GroupData represents a group master record from seeds/data/groups.json.
type GroupData struct {
	Slug          string `json:"slug"`
	Name          string `json:"name"`
	ShortName     string `json:"short_name"`
	ThemeColorHex string `json:"theme_color_hex"`
	DisplayOrder  int    `json:"display_order"`
}

// ColorData represents an official penlight color record from seeds/data/colors.json.
type ColorData struct {
	GroupSlug    string `json:"group_slug"`
	Name         string `json:"name"`
	HexCode      string `json:"hex_code"`
	DisplayOrder int    `json:"display_order"`
}

// PhotoTypeData represents a costume/photo category from seeds/data/photo_types.json.
type PhotoTypeData struct {
	GroupSlug    string `json:"group_slug"`
	Slug         string `json:"slug"`
	Name         string `json:"name"`
	DisplayOrder int    `json:"display_order"`
}

// ImageItem represents an image asset entry for a member.
type ImageItem struct {
	PhotoTypeSlug string `json:"photo_type_slug"`
	URL           string `json:"url"`
	IsPrimary     bool   `json:"is_primary"`
}

// MemberData represents an idol member record from seeds/data/members.json.
type MemberData struct {
	GroupSlug      string      `json:"group_slug"`
	FamilyName     string      `json:"family_name"`
	GivenName      string      `json:"given_name"`
	FamilyNameKana string      `json:"family_name_kana"`
	GivenNameKana  string      `json:"given_name_kana"`
	Generation     int         `json:"generation"`
	Status         string      `json:"status"`
	LeftColor      string      `json:"left_color"`
	RightColor     string      `json:"right_color"`
	Images         []ImageItem `json:"images"`
}

// Fixed namespaces for deterministic TypeID generation (Ref: ADR-0001, ADR-0021)
var (
	nsGroup     = uuid.MustParse("018f3a00-0000-7000-8000-000000000001")
	nsColor     = uuid.MustParse("018f3a00-0000-7000-8000-000000000002")
	nsMember    = uuid.MustParse("018f3a00-0000-7000-8000-000000000003")
	nsImage     = uuid.MustParse("018f3a00-0000-7000-8000-000000000004")
	nsPhotoType = uuid.MustParse("018f3a00-0000-7000-8000-000000000005")
)

func typeID(prefix string, u uuid.UUID) string {
	return fmt.Sprintf("%s_%s", prefix, strings.ReplaceAll(u.String(), "-", ""))
}

func main() {
	// 1. Read clean JSON sources
	var groups []GroupData
	readJSON("seeds/data/groups.json", &groups)

	var colors []ColorData
	readJSON("seeds/data/colors.json", &colors)

	var photoTypes []PhotoTypeData
	readJSON("seeds/data/photo_types.json", &photoTypes)

	var members []MemberData
	readJSON("seeds/data/members.json", &members)

	nowUTC := "2026-10-04T00:00:00Z"
	var sql []string
	sql = append(sql, "-- Generated by scripts/build_seed.go from seeds/data/*.json")
	sql = append(sql, "-- Master Data: Groups, Colors, PhotoTypes, Members, MemberImages, MasterVersions")
	sql = append(sql, "")

	// 2. Generate Groups SQL
	groupMap := make(map[string]string) // slug -> grp_<uuid>
	for _, g := range groups {
		gid := typeID("grp", uuid.NewSHA1(nsGroup, []byte(g.Slug)))
		groupMap[g.Slug] = gid

		sql = append(sql, fmt.Sprintf(
			"INSERT OR IGNORE INTO groups (id, name, short_name, slug, theme_color_hex, display_order, is_active, created_at, updated_at)\nVALUES ('%s', '%s', '%s', '%s', '%s', %d, 1, '%s', '%s');",
			gid, g.Name, g.ShortName, g.Slug, g.ThemeColorHex, g.DisplayOrder, nowUTC, nowUTC,
		))
	}

	// 3. Generate Colors SQL
	colorMap := make(map[string]string) // group_slug:color_name -> col_<uuid>
	sql = append(sql, "\n-- Official Penlight Colors")
	for _, c := range colors {
		gid, ok := groupMap[c.GroupSlug]
		if !ok {
			log.Fatalf("unknown group_slug: %s in colors", c.GroupSlug)
		}
		cid := typeID("col", uuid.NewSHA1(nsColor, []byte(fmt.Sprintf("%s:%s", c.GroupSlug, c.Name))))
		colorMap[fmt.Sprintf("%s:%s", c.GroupSlug, c.Name)] = cid

		sql = append(sql, fmt.Sprintf(
			"INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)\nVALUES ('%s', '%s', '%s', '%s', %d, '%s', '%s');",
			cid, gid, c.Name, c.HexCode, c.DisplayOrder, nowUTC, nowUTC,
		))
	}

	// 4. Generate PhotoTypes SQL
	photoTypeMap := make(map[string]string) // group_slug:photo_type_slug -> pht_<uuid>
	sql = append(sql, "\n-- Photo Types / Costumes (Ref: ADR-0021)")
	for _, pt := range photoTypes {
		gid, ok := groupMap[pt.GroupSlug]
		if !ok {
			log.Fatalf("unknown group_slug: %s in photo_types", pt.GroupSlug)
		}
		ptid := typeID("pht", uuid.NewSHA1(nsPhotoType, []byte(fmt.Sprintf("%s:%s", pt.GroupSlug, pt.Slug))))
		photoTypeMap[fmt.Sprintf("%s:%s", pt.GroupSlug, pt.Slug)] = ptid

		sql = append(sql, fmt.Sprintf(
			"INSERT OR IGNORE INTO photo_types (id, group_id, slug, name, display_order, created_at, updated_at)\nVALUES ('%s', '%s', '%s', '%s', %d, '%s', '%s');",
			ptid, gid, pt.Slug, pt.Name, pt.DisplayOrder, nowUTC, nowUTC,
		))
	}

	// 5. Generate Members & MemberImages SQL
	type ImageSource struct {
		ImageID       string `json:"image_id"`
		MemberID      string `json:"member_id"`
		Name          string `json:"name"`
		Group         string `json:"group"`
		PhotoTypeSlug string `json:"photo_type_slug"`
		URL           string `json:"url"`
		DestKey       string `json:"dest_key"`
	}
	var imageSources []ImageSource
	var imageSQL []string

	sql = append(sql, "\n-- Idol Members")
	for _, m := range members {
		gid, ok := groupMap[m.GroupSlug]
		if !ok {
			log.Fatalf("unknown group_slug: %s in members", m.GroupSlug)
		}
		fullName := fmt.Sprintf("%s%s", m.FamilyName, m.GivenName)
		mid := typeID("mem", uuid.NewSHA1(nsMember, []byte(fmt.Sprintf("%s:%s", m.GroupSlug, fullName))))

		leftColID, ok := colorMap[fmt.Sprintf("%s:%s", m.GroupSlug, m.LeftColor)]
		if !ok {
			log.Fatalf("missing left color %q for %s (%s)", m.LeftColor, fullName, m.GroupSlug)
		}
		rightColID, ok := colorMap[fmt.Sprintf("%s:%s", m.GroupSlug, m.RightColor)]
		if !ok {
			log.Fatalf("missing right color %q for %s (%s)", m.RightColor, fullName, m.GroupSlug)
		}

		sql = append(sql, fmt.Sprintf(
			"INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, created_at, updated_at)\nVALUES ('%s', '%s', '%s', '%s', '%s', '%s', %d, '%s', '%s', '%s', 0, '%s', '%s');",
			mid, gid, m.FamilyName, m.GivenName, m.FamilyNameKana, m.GivenNameKana, m.Generation, m.Status, leftColID, rightColID, nowUTC, nowUTC,
		))

		for orderIdx, img := range m.Images {
			ptid, ok := photoTypeMap[fmt.Sprintf("%s:%s", m.GroupSlug, img.PhotoTypeSlug)]
			if !ok {
				log.Fatalf("missing photo_type %q for member %s (%s)", img.PhotoTypeSlug, fullName, m.GroupSlug)
			}

			imgID := typeID("img", uuid.NewSHA1(nsImage, []byte(fmt.Sprintf("%s:%s", mid, img.URL))))
			imgKey := fmt.Sprintf("%s.webp", imgID)
			isPrimaryInt := 0
			if img.IsPrimary {
				isPrimaryInt = 1
			}

			imageSQL = append(imageSQL, fmt.Sprintf(
				"INSERT OR IGNORE INTO member_images (id, member_id, photo_type_id, image_key, is_primary, display_order, created_at, updated_at)\nVALUES ('%s', '%s', '%s', '%s', %d, %d, '%s', '%s');",
				imgID, mid, ptid, imgKey, isPrimaryInt, orderIdx, nowUTC, nowUTC,
			))

			imageSources = append(imageSources, ImageSource{
				ImageID:       imgID,
				MemberID:      mid,
				Name:          fullName,
				Group:         m.GroupSlug,
				PhotoTypeSlug: img.PhotoTypeSlug,
				URL:           img.URL,
				DestKey:       imgKey,
			})
		}
	}

	sql = append(sql, "\n-- Member Images (1:N, Ref: ADR-0021)")
	sql = append(sql, imageSQL...)

	// 6. Generate MasterVersion SQL
	sql = append(sql, "\n-- Master Version (Ref: ADR-0021)")
	sql = append(sql, fmt.Sprintf(
		"INSERT OR REPLACE INTO master_versions (id, version, updated_at)\nVALUES ('current', '2026.10.04-2', '%s');",
		nowUTC,
	))

	// 7. Output seed.sql
	seedSQLPath := filepath.Join("seeds", "seed.sql")
	if err := os.WriteFile(seedSQLPath, []byte(strings.Join(sql, "\n")+"\n"), 0o644); err != nil {
		log.Fatalf("failed to write %s: %v", seedSQLPath, err)
	}
	fmt.Printf("Generated %s: %d groups, %d colors, %d photo_types, %d members, %d images\n", seedSQLPath, len(groups), len(colors), len(photoTypes), len(members), len(imageSources))

	// 8. Output image_sources.json
	imgSrcJSON, _ := json.MarshalIndent(imageSources, "", "  ")
	imgSrcJSON = append(imgSrcJSON, '\n')
	_ = os.WriteFile(filepath.Join("seeds", "data", "image_sources.json"), imgSrcJSON, 0o644)
	_ = os.WriteFile(filepath.Join("data", "image_sources.json"), imgSrcJSON, 0o644)
}

func readJSON(path string, target any) {
	bytes, err := os.ReadFile(path)
	if err != nil {
		log.Fatalf("failed to read %s: %v", path, err)
	}
	if err := json.Unmarshal(bytes, target); err != nil {
		log.Fatalf("failed to parse %s: %v", path, err)
	}
}
