//go:build ignore

package main

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"github.com/google/uuid"
)

// BQTableData represents the JSON structure exported from BigQuery REST API.
type BQTableData struct {
	Rows []struct {
		F []struct {
			V string `json:"v"`
		} `json:"f"`
	} `json:"rows"`
}

// MemberReading defines the family/given name separation and hiragana reading.
type MemberReading struct {
	FamilyName     string `json:"family_name"`
	GivenName      string `json:"given_name"`
	FamilyNameKana string `json:"family_name_kana"`
	GivenNameKana  string `json:"given_name_kana"`
}

// GroupConfig defines a group to import loaded from seeds/data/groups.json.
type GroupConfig struct {
	Slug          string `json:"slug"`
	Name          string `json:"name"`
	ShortName     string `json:"short_name"`
	ThemeColorHex string `json:"theme_color_hex"`
	DisplayOrder  int    `json:"display_order"`
	ColorsFile    string `json:"colors_file"`
	MembersFile   string `json:"members_file"`
}

// Fixed namespace for deterministic TypeID generation
var (
	nsGroup  = uuid.MustParse("018f3a00-0000-7000-8000-000000000001")
	nsColor  = uuid.MustParse("018f3a00-0000-7000-8000-000000000002")
	nsMember = uuid.MustParse("018f3a00-0000-7000-8000-000000000003")
)

func parseGeneration(genStr string) int {
	cleaned := strings.TrimSuffix(genStr, "st")
	cleaned = strings.TrimSuffix(cleaned, "nd")
	cleaned = strings.TrimSuffix(cleaned, "rd")
	cleaned = strings.TrimSuffix(cleaned, "th")
	val, err := strconv.Atoi(cleaned)
	if err != nil {
		return 1
	}
	return val
}

func normalizeHex(hex string) string {
	hex = strings.TrimSpace(hex)
	if !strings.HasPrefix(hex, "#") {
		hex = "#" + hex
	}
	if len(hex) == 6 {
		hex = "#0" + hex[1:]
	}
	return strings.ToUpper(hex)
}

func main() {
	// 1. Load external metadata
	groupsBytes, err := os.ReadFile("seeds/data/groups.json")
	if err != nil {
		log.Fatalf("failed to read seeds/data/groups.json: %v", err)
	}
	var groups []GroupConfig
	if err := json.Unmarshal(groupsBytes, &groups); err != nil {
		log.Fatalf("failed to parse seeds/data/groups.json: %v", err)
	}

	readingsBytes, err := os.ReadFile("seeds/data/readings.json")
	if err != nil {
		log.Fatalf("failed to read seeds/data/readings.json: %v", err)
	}
	var memberReadings map[string]MemberReading
	if err := json.Unmarshal(readingsBytes, &memberReadings); err != nil {
		log.Fatalf("failed to parse seeds/data/readings.json: %v", err)
	}

	var sqlStatements []string
	sqlStatements = append(sqlStatements, "-- Generated by scripts/import_bq_seeds.go")
	sqlStatements = append(sqlStatements, "-- Sources: BigQuery exports + seeds/data/{groups,readings}.json")
	sqlStatements = append(sqlStatements, "")

	type ImageSource struct {
		MemberID string `json:"member_id"`
		Name     string `json:"name"`
		Group    string `json:"group"`
		URL      string `json:"url"`
		Type     string `json:"type"`
		DestKey  string `json:"dest_key"`
	}
	var imageSources []ImageSource

	nowUTC := "2026-10-04T00:00:00Z"

	for _, g := range groups {
		groupID := fmt.Sprintf("grp_%s", strings.ReplaceAll(uuid.NewSHA1(nsGroup, []byte(g.Slug)).String(), "-", ""))

		sqlStatements = append(sqlStatements, fmt.Sprintf(
			"INSERT OR IGNORE INTO groups (id, name, short_name, slug, theme_color_hex, display_order, is_active, created_at, updated_at)\nVALUES ('%s', '%s', '%s', '%s', '%s', %d, 1, '%s', '%s');",
			groupID, g.Name, g.ShortName, g.Slug, g.ThemeColorHex, g.DisplayOrder, nowUTC, nowUTC,
		))

		// 2. Process Colors
		colorsDataBytes, err := os.ReadFile(g.ColorsFile)
		if err != nil {
			log.Fatalf("failed to read colors file %s: %v", g.ColorsFile, err)
		}
		var colorsData BQTableData
		if err := json.Unmarshal(colorsDataBytes, &colorsData); err != nil {
			log.Fatalf("failed to unmarshal colors json: %v", err)
		}

		colorIDMap := make(map[string]string)
		type colorItem struct {
			bqID  int
			name  string
			hex   string
			order int
		}
		var colorList []colorItem
		for _, row := range colorsData.Rows {
			bqID, _ := strconv.Atoi(row.F[0].V)
			nameJa := row.F[1].V
			hexVal := normalizeHex(row.F[3].V)
			colorList = append(colorList, colorItem{
				bqID:  bqID,
				name:  nameJa,
				hex:   hexVal,
				order: bqID,
			})
		}
		sort.Slice(colorList, func(i, j int) bool {
			return colorList[i].order < colorList[j].order
		})

		sqlStatements = append(sqlStatements, fmt.Sprintf("\n-- Colors for %s", g.Name))
		for _, col := range colorList {
			colUUIDKey := fmt.Sprintf("%s:%s", g.Slug, col.name)
			colID := fmt.Sprintf("col_%s", strings.ReplaceAll(uuid.NewSHA1(nsColor, []byte(colUUIDKey)).String(), "-", ""))
			colorIDMap[strconv.Itoa(col.bqID)] = colID

			sqlStatements = append(sqlStatements, fmt.Sprintf(
				"INSERT OR IGNORE INTO colors (id, group_id, name, hex_code, display_order, created_at, updated_at)\nVALUES ('%s', '%s', '%s', '%s', %d, '%s', '%s');",
				colID, groupID, col.name, col.hex, col.order, nowUTC, nowUTC,
			))
		}

		// 3. Process Members
		membersDataBytes, err := os.ReadFile(g.MembersFile)
		if err != nil {
			log.Fatalf("failed to read members file %s: %v", g.MembersFile, err)
		}
		var membersData BQTableData
		if err := json.Unmarshal(membersDataBytes, &membersData); err != nil {
			log.Fatalf("failed to unmarshal members json: %v", err)
		}

		type memberRowData struct {
			id       string
			name     string
			gen      string
			grad     bool
			p1       string
			p2       string
			imgType  string
			imageURL string
		}

		memberMap := make(map[string][]memberRowData)
		for _, row := range membersData.Rows {
			mid := row.F[0].V
			name := row.F[1].V
			gen := row.F[4].V
			grad := row.F[5].V == "true"
			p1 := row.F[6].V
			p2 := row.F[7].V
			imgType := row.F[8].V
			imageURL := row.F[9].V

			memberMap[name] = append(memberMap[name], memberRowData{
				id:       mid,
				name:     name,
				gen:      gen,
				grad:     grad,
				p1:       p1,
				p2:       p2,
				imgType:  imgType,
				imageURL: imageURL,
			})
		}

		var memberNames []string
		for name := range memberMap {
			memberNames = append(memberNames, name)
		}
		sort.Strings(memberNames)

		sqlStatements = append(sqlStatements, fmt.Sprintf("\n-- Members for %s", g.Name))
		for _, name := range memberNames {
			rows := memberMap[name]
			first := rows[0]

			bestRow := first
			typePreference := []string{"13thSingle", "5thMember", "2ndAlbum", "5thHinatansai", "4thTowel"}
			for _, pref := range typePreference {
				found := false
				for _, r := range rows {
					if r.imgType == pref {
						bestRow = r
						found = true
						break
					}
				}
				if found {
					break
				}
			}

			memUUIDKey := fmt.Sprintf("%s:%s", g.Slug, name)
			memID := fmt.Sprintf("mem_%s", strings.ReplaceAll(uuid.NewSHA1(nsMember, []byte(memUUIDKey)).String(), "-", ""))

			reading, ok := memberReadings[name]
			if !ok {
				log.Fatalf("missing reading in seeds/data/readings.json for member: %s", name)
			}

			genInt := parseGeneration(first.gen)
			status := "active"
			if first.grad {
				status = "graduated"
			}

			leftColID, ok := colorIDMap[first.p1]
			if !ok {
				log.Fatalf("missing color %s for member %s", first.p1, name)
			}
			rightColID, ok := colorIDMap[first.p2]
			if !ok {
				log.Fatalf("missing color %s for member %s", first.p2, name)
			}

			imageKey := fmt.Sprintf("%s.webp", memID)

			imageSources = append(imageSources, ImageSource{
				MemberID: memID,
				Name:     name,
				Group:    g.Slug,
				URL:      bestRow.imageURL,
				Type:     bestRow.imgType,
				DestKey:  imageKey,
			})

			sqlStatements = append(sqlStatements, fmt.Sprintf(
				"INSERT OR IGNORE INTO members (id, group_id, family_name, given_name, family_name_kana, given_name_kana, generation, status, left_color_id, right_color_id, ordered, image_key, created_at, updated_at)\nVALUES ('%s', '%s', '%s', '%s', '%s', '%s', %d, '%s', '%s', '%s', 0, '%s', '%s', '%s');",
				memID, groupID, reading.FamilyName, reading.GivenName, reading.FamilyNameKana, reading.GivenNameKana, genInt, status, leftColID, rightColID, imageKey, nowUTC, nowUTC,
			))
		}
	}

	seedSQLPath := filepath.Join("seeds", "seed.sql")
	if err := os.WriteFile(seedSQLPath, []byte(strings.Join(sqlStatements, "\n")+"\n"), 0o644); err != nil {
		log.Fatalf("failed to write seed sql: %v", err)
	}
	fmt.Printf("Successfully generated %s (%d lines)\n", seedSQLPath, len(sqlStatements))

	imgSrcJSON, err := json.MarshalIndent(imageSources, "", "  ")
	if err != nil {
		log.Fatalf("failed to marshal image sources: %v", err)
	}
	imgSrcPath := filepath.Join("data", "image_sources.json")
	if err := os.WriteFile(imgSrcPath, imgSrcJSON, 0o644); err != nil {
		log.Fatalf("failed to write image sources json: %v", err)
	}
	fmt.Printf("Successfully generated %s (%d items)\n", imgSrcPath, len(imageSources))
}
